import CubeChains.Machinery.Braid.Artin
import Mathlib.Order.Fin.Basic
import Mathlib.Order.WellFounded
import Mathlib.Data.Fin.Tuple.Sort

/-!
# Machinery/Braid/Generated — adjacent transpositions generate the braid group

`Braid n` is generated by the simple braids `ofPerm (adjT i)`.  The bridge is length-additivity:
every `ofPerm σ` factors, one adjacent descent at a time, into a length-additive product of the
generators (`ofPerm_mem_closure_adjT`), by strong induction on `permLen σ`.
-/

namespace CubeChains

open Equiv

variable {n : ℕ}

/-- Adjacent ascent at every step upgrades to full strict monotonicity. -/
theorem strictMono_of_adjacent (σ : Perm (Fin n))
    (h : ∀ i : Fin (n - 1), σ (adjLo i) < σ (adjHi i)) : StrictMono (⇑σ : Fin n → Fin n) := by
  cases n with
  | zero => intro a; exact a.elim0
  | succ m =>
    rw [Fin.strictMono_iff_lt_succ]
    intro i
    have hi := h i
    rwa [show (adjLo i : Fin (m + 1)) = Fin.castSucc i from Fin.ext rfl,
      show (adjHi i : Fin (m + 1)) = Fin.succ i from Fin.ext rfl] at hi

/-- No adjacent descent forces the identity. -/
theorem eq_one_of_no_adjacent_descent (σ : Perm (Fin n))
    (h : ∀ i : Fin (n - 1), ¬ σ (adjHi i) < σ (adjLo i)) : σ = 1 :=
  (Equiv.Perm.monotone_iff σ).mp (strictMono_of_adjacent σ fun i =>
    lt_of_le_of_ne (not_lt.mp (h i)) fun heq => adjLo_ne_adjHi i (σ.injective heq)).monotone

/-- A permutation of length `0` is the identity. -/
theorem eq_one_of_permLen_eq_zero (σ : Perm (Fin n)) (h : permLen σ = 0) : σ = 1 := by
  apply eq_one_of_no_adjacent_descent
  intro i hcon
  have hmem : (adjLo i, adjHi i) ∈ inversions σ := by
    simp only [inversions, Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨by rw [Fin.lt_def, adjLo_val, adjHi_val]; omega, hcon⟩
  have hpos : 0 < permLen σ := by rw [permLen]; exact Finset.card_pos.mpr ⟨_, hmem⟩
  omega

/-- A permutation of positive length has an adjacent descent. -/
theorem exists_adjacent_descent (σ : Perm (Fin n)) (h : 0 < permLen σ) :
    ∃ i : Fin (n - 1), σ (adjHi i) < σ (adjLo i) := by
  by_contra hcon
  rw [not_exists] at hcon
  rw [eq_one_of_no_adjacent_descent σ hcon, permLen_one] at h
  exact lt_irrefl 0 h

/-! ## Facing off a descent

Both facts below are `permLen_mul_adjT` / `ofPerm_mul_adjT` at `A := σ * adjT i`, read back
through `mul_adjT_adjT`. -/

/-- Undoing a descent leaves an ascent: `σ * adjT i` rises across the swapped pair. -/
theorem adjT_ascent_of_descent {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (hdesc : σ (adjHi i) < σ (adjLo i)) :
    (σ * adjT i) (adjLo i) < (σ * adjT i) (adjHi i) := by
  simp only [Perm.mul_apply, adjT_lo, adjT_hi]; exact hdesc

/-- Facing a descent `σ (adjHi i) < σ (adjLo i)` off the right drops the length by one. -/
theorem permLen_mul_adjT_of_descent {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (hdesc : σ (adjHi i) < σ (adjLo i)) : permLen σ = permLen (σ * adjT i) + 1 := by
  have h := permLen_mul_adjT (adjT_ascent_of_descent hdesc)
  rwa [mul_adjT_adjT] at h

/-- **…and only an adjacent transposition crosses exactly one pair**: the converse of
`permLen_adjT` (`Machinery/Braid/Artin`, whose imports cannot reach the descent recursion).  Peel
the descent a length-one permutation must have and nothing is left. -/
theorem eq_adjT_of_permLen_eq_one {σ : Perm (Fin n)} (h : permLen σ = 1) :
    ∃ i : Fin (n - 1), σ = adjT i := by
  obtain ⟨i, hi⟩ := exists_adjacent_descent σ (by omega)
  refine ⟨i, ?_⟩
  have h0 : permLen (σ * adjT i) = 0 := by
    have := permLen_mul_adjT_of_descent hi; omega
  rw [← mul_adjT_adjT σ i, eq_one_of_permLen_eq_zero _ h0, one_mul]

/-- Peeling that descent off `ofPerm` is length-additive (the germ relation). -/
theorem ofPerm_mul_adjT_of_descent {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (hdesc : σ (adjHi i) < σ (adjLo i)) :
    ofPerm (σ * adjT i) * ofPerm (adjT i) = ofPerm σ := by
  have h := ofPerm_mul_adjT (adjT_ascent_of_descent hdesc)
  rwa [mul_adjT_adjT] at h

/-- **Adjacent transpositions generate `Braid n`.**  Every simple braid lies in the subgroup they
generate: peel off one adjacent descent at a time, each step length-additive. -/
theorem ofPerm_mem_closure_adjT (n : ℕ) (σ : Perm (Fin n)) :
    ofPerm σ ∈ Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i))) := by
  set S := Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i))) with hS
  induction σ using permLen_strongRec with
  | _ σ ih =>
    rcases Nat.eq_zero_or_pos (permLen σ) with h0 | hpos
    · rw [eq_one_of_permLen_eq_zero σ h0, ofPerm_one]
      exact one_mem S
    · obtain ⟨i, hdesc⟩ := exists_adjacent_descent σ hpos
      have hlen := permLen_mul_adjT_of_descent hdesc
      rw [← ofPerm_mul_adjT_of_descent hdesc]
      exact mul_mem (ih (σ * adjT i) (by omega))
        (Subgroup.subset_closure (Set.mem_range_self i))

/-- **The length decides the direction of a simple swap**: `adjT i` either raises the length by
one, and then `σ` ascends across the pair it names, or lowers it by one, and then `σ` descends.
There is no third option, since the two endpoints are distinct. -/
theorem ascent_iff_permLen_mul_adjT {σ : Perm (Fin n)} {i : Fin (n - 1)} :
    σ (adjLo i) < σ (adjHi i) ↔ permLen (σ * adjT i) = permLen σ + 1 := by
  refine ⟨permLen_mul_adjT, fun h => ?_⟩
  rcases lt_trichotomy (σ (adjLo i)) (σ (adjHi i)) with h1 | h1 | h1
  · exact h1
  · exact absurd (σ.injective h1) (adjLo_ne_adjHi i)
  · have := permLen_mul_adjT_of_descent h1; omega

theorem ascent_of_permLen_mul_adjT {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (h : permLen (σ * adjT i) = permLen σ + 1) : σ (adjLo i) < σ (adjHi i) :=
  ascent_iff_permLen_mul_adjT.mpr h

/-- …and the descent reading of the same trichotomy. -/
theorem descent_of_permLen_drop {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (h : permLen (σ * adjT i) + 1 = permLen σ) : σ (adjHi i) < σ (adjLo i) := by
  by_contra hc
  rcases eq_or_lt_of_le (not_lt.mp hc) with h1 | h1
  · exact adjLo_ne_adjHi i (σ.injective h1)
  · have := permLen_mul_adjT h1; omega

/-- **Adjacent transpositions generate `Braid n`.** -/
theorem Braid.eq_closure_ofPerm_adjT (n : ℕ) :
    Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i)))
      = (⊤ : Subgroup (Braid n)) := by
  refine le_antisymm le_top ?_
  rw [← closure_range_ofPerm, Subgroup.closure_le]
  rintro x ⟨σ, rfl⟩
  exact ofPerm_mem_closure_adjT n σ

end CubeChains
