import CubeChains.Machinery.Braid.Artin
import Mathlib.Order.Fin.Basic
import Mathlib.Order.WellFounded
import Mathlib.Data.Fin.Tuple.Sort

/-!
# Machinery/Braid/Generated — adjacent transpositions generate the braid group

`Braid n` is generated by the simple braids `ofPerm (adjT i)`.  The bridge is length-additivity:
every `ofPerm σ` factors, one adjacent descent at a time, into a length-additive product of the
generators (`ofPerm_mem_closure_adjT`), by strong induction on `permLen σ`.
-/

namespace CubeChains

open Equiv

variable {n : ℕ}

/-- Adjacent ascent at every step upgrades to full strict monotonicity. -/
theorem strictMono_of_adjacent (σ : Perm (Fin n))
    (h : ∀ i : Fin (n - 1), σ (adjLo i) < σ (adjHi i)) : StrictMono (⇑σ : Fin n → Fin n) := by
  cases n with
  | zero => intro a; exact a.elim0
  | succ m =>
    rw [Fin.strictMono_iff_lt_succ]
    intro i
    have hi := h i
    rwa [show (adjLo i : Fin (m + 1)) = Fin.castSucc i from Fin.ext rfl,
      show (adjHi i : Fin (m + 1)) = Fin.succ i from Fin.ext rfl] at hi

/-- No adjacent descent forces the identity. -/
theorem eq_one_of_no_adjacent_descent (σ : Perm (Fin n))
    (h : ∀ i : Fin (n - 1), ¬ σ (adjHi i) < σ (adjLo i)) : σ = 1 :=
  (Equiv.Perm.monotone_iff σ).mp (strictMono_of_adjacent σ fun i =>
    lt_of_le_of_ne (not_lt.mp (h i)) fun heq => adjLo_ne_adjHi i (σ.injective heq)).monotone

/-- A permutation of length `0` is the identity. -/
theorem eq_one_of_permLen_eq_zero (σ : Perm (Fin n)) (h : permLen σ = 0) : σ = 1 := by
  apply eq_one_of_no_adjacent_descent
  intro i hcon
  have hmem : (adjLo i, adjHi i) ∈ inversions σ := by
    simp only [inversions, Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨by rw [Fin.lt_def, adjLo_val, adjHi_val]; omega, hcon⟩
  have hpos : 0 < permLen σ := by rw [permLen]; exact Finset.card_pos.mpr ⟨_, hmem⟩
  omega

/-- A permutation of positive length has an adjacent descent. -/
theorem exists_adjacent_descent (σ : Perm (Fin n)) (h : 0 < permLen σ) :
    ∃ i : Fin (n - 1), σ (adjHi i) < σ (adjLo i) := by
  by_contra hcon
  rw [not_exists] at hcon
  rw [eq_one_of_no_adjacent_descent σ hcon, permLen_one] at h
  exact lt_irrefl 0 h

/-! ## Facing off a descent

Both facts below are `permLen_mul_adjT` / `ofPerm_mul_adjT` at `A := σ * adjT i`, read back
through `mul_adjT_adjT`. -/

/-- Undoing a descent leaves an ascent: `σ * adjT i` rises across the swapped pair. -/
theorem adjT_ascent_of_descent {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (hdesc : σ (adjHi i) < σ (adjLo i)) :
    (σ * adjT i) (adjLo i) < (σ * adjT i) (adjHi i) := by
  simp only [Perm.mul_apply, adjT_lo, adjT_hi]; exact hdesc

/-- Facing a descent `σ (adjHi i) < σ (adjLo i)` off the right drops the length by one. -/
theorem permLen_mul_adjT_of_descent {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (hdesc : σ (adjHi i) < σ (adjLo i)) : permLen σ = permLen (σ * adjT i) + 1 := by
  have h := permLen_mul_adjT (adjT_ascent_of_descent hdesc)
  rwa [mul_adjT_adjT] at h

/-- **A simple swap is an ascent or a descent**: its two endpoints are distinct. -/
theorem ascent_or_descent (σ : Perm (Fin n)) (i : Fin (n - 1)) :
    σ (adjLo i) < σ (adjHi i) ∨ σ (adjHi i) < σ (adjLo i) :=
  lt_or_gt_of_ne fun h => adjLo_ne_adjHi i (σ.injective h)

/-- **The length decides the direction of a simple swap**: appending `adjT i` raises the length by
one across an ascent (`permLen_mul_adjT`) and lowers it across a descent
(`permLen_mul_adjT_of_descent`), so either reading of the length names its direction. -/
theorem ascent_of_permLen_mul_adjT {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (h : permLen (σ * adjT i) = permLen σ + 1) : σ (adjLo i) < σ (adjHi i) :=
  (ascent_or_descent σ i).resolve_right fun hd => by
    have := permLen_mul_adjT_of_descent hd; omega

theorem descent_of_permLen_drop {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (h : permLen (σ * adjT i) + 1 = permLen σ) : σ (adjHi i) < σ (adjLo i) :=
  (ascent_or_descent σ i).resolve_left fun ha => by
    have := permLen_mul_adjT ha; omega

/-- **…and only an adjacent transposition crosses exactly one pair**: the converse of
`permLen_adjT` (`Machinery/Braid/Artin`, whose imports cannot reach the descent recursion).  Peel
the descent a length-one permutation must have and nothing is left. -/
theorem eq_adjT_of_permLen_eq_one {σ : Perm (Fin n)} (h : permLen σ = 1) :
    ∃ i : Fin (n - 1), σ = adjT i := by
  obtain ⟨i, hi⟩ := exists_adjacent_descent σ (by omega)
  refine ⟨i, ?_⟩
  have h0 : permLen (σ * adjT i) = 0 := by
    have := permLen_mul_adjT_of_descent hi; omega
  rw [← mul_adjT_adjT σ i, eq_one_of_permLen_eq_zero _ h0, one_mul]

/-- Peeling that descent off `ofPerm` is length-additive (the germ relation). -/
theorem ofPerm_mul_adjT_of_descent {σ : Perm (Fin n)} {i : Fin (n - 1)}
    (hdesc : σ (adjHi i) < σ (adjLo i)) :
    ofPerm (σ * adjT i) * ofPerm (adjT i) = ofPerm σ := by
  have h := ofPerm_mul_adjT (adjT_ascent_of_descent hdesc)
  rwa [mul_adjT_adjT] at h

/-- **Adjacent transpositions generate `Braid n`.**  Every simple braid lies in the subgroup they
generate: peel off one adjacent descent at a time, each step length-additive. -/
theorem ofPerm_mem_closure_adjT (n : ℕ) (σ : Perm (Fin n)) :
    ofPerm σ ∈ Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i))) := by
  set S := Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i))) with hS
  induction σ using permLen_strongRec with
  | _ σ ih =>
    rcases Nat.eq_zero_or_pos (permLen σ) with h0 | hpos
    · rw [eq_one_of_permLen_eq_zero σ h0, ofPerm_one]
      exact one_mem S
    · obtain ⟨i, hdesc⟩ := exists_adjacent_descent σ hpos
      have hlen := permLen_mul_adjT_of_descent hdesc
      rw [← ofPerm_mul_adjT_of_descent hdesc]
      exact mul_mem (ih (σ * adjT i) (by omega))
        (Subgroup.subset_closure (Set.mem_range_self i))

/-! ## The two-descent window

Two descents `i < j` of `u` are far apart or consecutive, and each leaves a shape behind: the square
`u sᵢ sⱼ = u sⱼ sᵢ`, or the hexagon `u sᵢ sⱼ sᵢ = u sⱼ sᵢ sⱼ`.  The lemmas below are the interior
descents those shapes pass through, read off the three values `u (adjLo i)`, `u (adjHi i)`,
`u (adjHi j)` that the window sorts. -/

/-- A swap two apart leaves another index's descent alone. -/
theorem descent_mul_adjT_of_far {u : Perm (Fin n)} {k l : Fin (n - 1)} (h1 : (l : ℕ) ≠ (k : ℕ))
    (h2 : (l : ℕ) ≠ (k : ℕ) + 1) (h3 : (l : ℕ) + 1 ≠ (k : ℕ))
    (hl : u (adjHi l) < u (adjLo l)) : (u * adjT k) (adjHi l) < (u * adjT k) (adjLo l) := by
  rw [Perm.mul_apply, Perm.mul_apply, adjT_adjLo_of_ne h1 h2, adjT_adjHi_of_ne h3 (by omega)]
  exact hl

/-- Undoing the first of two consecutive descents leaves the second one a descent. -/
theorem descent_mul_adjT_braid₁ {u : Perm (Fin n)} {i j : Fin (n - 1)} (hij : (j : ℕ) = (i : ℕ) + 1)
    (hi : u (adjHi i) < u (adjLo i)) (hj : u (adjHi j) < u (adjLo j)) :
    (u * adjT i) (adjHi j) < (u * adjT i) (adjLo j) := by
  have hm := adjLo_eq_adjHi hij
  have h1 : adjT i (adjLo j) = adjLo i := by rw [hm]; exact adjT_hi i
  rw [Perm.mul_apply, Perm.mul_apply, h1, adjT_adjHi_of_ne (by omega) (by omega)]
  rw [hm] at hj
  exact hj.trans hi

/-- …and undoing that one leaves the first a descent again: three steps sort the window. -/
theorem descent_mul_adjT_braid₂ {u : Perm (Fin n)} {i j : Fin (n - 1)} (hij : (j : ℕ) = (i : ℕ) + 1)
    (hj : u (adjHi j) < u (adjLo j)) :
    (u * adjT i * adjT j) (adjHi i) < (u * adjT i * adjT j) (adjLo i) := by
  have hm := adjLo_eq_adjHi hij
  have h2 : adjT j (adjHi i) = adjHi j := by rw [← hm]; exact adjT_lo j
  rw [Perm.mul_apply, Perm.mul_apply, Perm.mul_apply, Perm.mul_apply,
    adjT_adjLo_of_ne (by omega) (by omega), h2, adjT_lo i,
    adjT_adjHi_of_ne (k := i) (l := j) (by omega) (by omega)]
  rw [hm] at hj
  exact hj

/-- The first of the two again, with the consecutive indices swapped — the hexagon's other leg. -/
theorem descent_mul_adjT_braid₃ {u : Perm (Fin n)} {i j : Fin (n - 1)} (hij : (j : ℕ) = (i : ℕ) + 1)
    (hi : u (adjHi i) < u (adjLo i)) (hj : u (adjHi j) < u (adjLo j)) :
    (u * adjT j) (adjHi i) < (u * adjT j) (adjLo i) := by
  have hm := adjLo_eq_adjHi hij
  have h1 : adjT j (adjHi i) = adjHi j := by rw [← hm]; exact adjT_lo j
  rw [Perm.mul_apply, Perm.mul_apply, h1, adjT_adjLo_of_ne (by omega) (by omega)]
  rw [hm] at hj
  exact hj.trans hi

/-- …and the second. -/
theorem descent_mul_adjT_braid₄ {u : Perm (Fin n)} {i j : Fin (n - 1)} (hij : (j : ℕ) = (i : ℕ) + 1)
    (hi : u (adjHi i) < u (adjLo i)) :
    (u * adjT j * adjT i) (adjHi j) < (u * adjT j * adjT i) (adjLo j) := by
  have hm := adjLo_eq_adjHi hij
  have h1 : adjT i (adjLo j) = adjLo i := by rw [hm]; exact adjT_hi i
  rw [Perm.mul_apply, Perm.mul_apply, Perm.mul_apply, Perm.mul_apply,
    adjT_adjHi_of_ne (k := i) (l := j) (by omega) (by omega), adjT_hi j, h1,
    adjT_adjLo_of_ne (by omega) (by omega), hm]
  exact hi

/-- **Cuts apart: a crossing of length two inverting both is their commuting product.** -/
theorem eq_adjT_mul_adjT_of_descents {σ : Perm (Fin n)} {i j : Fin (n - 1)}
    (hfar : (i : ℕ) + 1 < (j : ℕ)) (hi : σ (adjHi i) < σ (adjLo i))
    (hj : σ (adjHi j) < σ (adjLo j)) (hlen : permLen σ = 2) : σ = adjT j * adjT i := by
  have hdj : (σ * adjT i) (adjHi j) < (σ * adjT i) (adjLo j) :=
    descent_mul_adjT_of_far (by omega) (by omega) (by omega) hj
  have h1 := permLen_mul_adjT_of_descent hi
  have h2 := permLen_mul_adjT_of_descent hdj
  have hone : σ * (adjT i * adjT j) = 1 := by
    rw [← mul_assoc]
    exact eq_one_of_permLen_eq_zero _ (by omega)
  rw [mul_eq_one_iff_eq_inv.mp hone, mul_inv_rev]
  simp only [adjT_inv]

/-- **Consecutive cuts: a crossing of length three inverting both is their braid word.** -/
theorem eq_braid_of_descents {σ : Perm (Fin n)} {i j : Fin (n - 1)}
    (hadj : (j : ℕ) = (i : ℕ) + 1) (hi : σ (adjHi i) < σ (adjLo i))
    (hj : σ (adjHi j) < σ (adjLo j)) (hlen : permLen σ = 3) :
    σ = adjT i * adjT j * adjT i := by
  have d1 := permLen_mul_adjT_of_descent (descent_mul_adjT_braid₁ hadj hi hj)
  have d2 := permLen_mul_adjT_of_descent (descent_mul_adjT_braid₂ hadj hj)
  have h1 := permLen_mul_adjT_of_descent hi
  have hone : σ * (adjT i * adjT j * adjT i) = 1 := by
    rw [← mul_assoc, ← mul_assoc]
    exact eq_one_of_permLen_eq_zero _ (by omega)
  rw [mul_eq_one_iff_eq_inv.mp hone, mul_inv_rev, mul_inv_rev]
  simp only [adjT_inv]
  rw [← mul_assoc]

/-- **Adjacent transpositions generate `Braid n`.** -/
theorem Braid.eq_closure_ofPerm_adjT (n : ℕ) :
    Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i)))
      = (⊤ : Subgroup (Braid n)) := by
  refine le_antisymm le_top ?_
  rw [← closure_range_ofPerm, Subgroup.closure_le]
  rintro x ⟨σ, rfl⟩
  exact ofPerm_mem_closure_adjT n σ

end CubeChains
