import CubeChains.Research.Scratch.Cyl8_MooreMonoid

/-!
# Cyl13_Structure — special algebraic properties of the pointed-endofunctor monoid

Scratch investigation (RESULT 2 / cylinder ⟹ pointed-functor program).  **Decoupled** from the
green build; build with `lake build CubeChains.Research.Scratch.Cyl13_Structure`.  Owns ONLY this
file and its `.md`.  Builds on Cyl1 (`objDataEquiv`, well-pointedness), Cyl5 (target thinness),
Cyl6 (the `Monoid (PointedEndofunctor 𝒞)` instance, `cylImage`) and Cyl8 (`mooreSubmonoid`).

We study `M := PointedEndofunctor (DPathGrpdR K)` under the Cyl6 monoid (composition) and its
cylinder-induced submonoid `mooreSubmonoid K = Submonoid.closure (cylImage K)`.  Question: what
special **algebraic** properties does it have?

## What is proven here (sorry-free)

1. **Units / maximal subgroup.**  `A` is a unit of `M` *iff its underlying endofunctor `A.F` is a
   strict isomorphism of categories* (invertible under `⋙` on the nose).  The point data is then
   automatically invertible (groupoid base) — units are detected by `F` alone.
   - `isUnit_F_of_isUnit` : a unit's `F` is invertible in the functor-composition monoid.
   - `isUnit_of_strictInv` : on a groupoid base, a strict-iso `F` *is* a unit (inverse built
     explicitly).
   - `unitsGroup` is the maximal subgroup `IsUnit.submonoid M` (mathlib `Group` instance).
   - **The monoid is NOT a group**: `not_group_M` exhibits a non-invertible element — any
     `pointedOfPaths` whose `F` is not a strict iso (e.g. the tautological double of a vertex,
     `objMap` non-injective ⟹ `F` non-injective on objects ⟹ not a unit).

2. **Idempotents.**  `IsIdempotentElem A ↔ A.F ⋙ A.F = A.F` *plus* a point condition; via mathlib
   `IsIdempotentElem.iff_eq_one_of_isUnit`, **every idempotent UNIT is `1`**.  In particular the
   only idempotent in the group of units is `1`.  For the cylinder: a non-`1` idempotent would need
   `A.F` an idempotent-but-not-identity endofunctor, which a `pointedOfPaths` whose `F ≅ 𝟭` (always,
   groupoid base) can only achieve when `F = 𝟭`, forcing `A = 1` on objects — discussed.

3. **Well-pointedness.**  Settled via `Cyl1.isWellPointed_iff`: the cylinder's `(F₀, η)` reduces to
   the generator equation `F.map (η x) = pt.app (F₀ x)`.

4. **Commutativity / generation.**  The monoid is **non-commutative** in general (the product object
   map STACKS the two endofunctors, `B.F.obj (A.F.obj …) ≠ A.F.obj (B.F.obj …)`); `mooreSubmonoid`
   is generated by the *elementary* (length-1) cylinders (`Cyl8.mooreSubmonoid_eq_closure`).

**Layer:** Research/Scratch (decoupled).  **Imports:** `Cyl8_MooreMonoid` (hence Cyl1/5/6/7).
-/

open CategoryTheory Operations
open CubeChain

universe v u

namespace Cyl13

/-! ## 1. Units of the pointed-endofunctor monoid

`M = PointedEndofunctor 𝒞` is a strict monoid (Cyl6): `1 = ⟨𝟭, 𝟙⟩`, `A * B = ⟨A.F ⋙ B.F, …⟩`.
Because `1.F = 𝟭` *on the nose* and `(A * B).F = A.F ⋙ B.F`, a unit's `F` is forced to be a
**strict isomorphism of categories** (invertible functor under `⋙`).  Conversely, on a groupoid
base any strict-iso `F` extends to a unit: the point obstruction vanishes because every point is an
iso. -/

section Units

variable {𝒞 : Type u} [Category.{v} 𝒞]

/-- **Necessary condition for a unit: `F` is a strict iso of categories.**  If `A` is a unit of the
pointed-endofunctor monoid (with monoid-inverse `B`), then `A.F ⋙ B.F = 𝟭` and `B.F ⋙ A.F = 𝟭`
*on the nose* — `A.F` is an isomorphism of categories.  This is just projecting the two unit
equations `A * B = 1`, `B * A = 1` onto the `F` field (`Cyl6.mul_F`, `Cyl6.one_F`). -/
theorem strictInv_F_of_unit {A B : PointedEndofunctor 𝒞} (h₁ : A * B = 1) (h₂ : B * A = 1) :
    A.F ⋙ B.F = 𝟭 𝒞 ∧ B.F ⋙ A.F = 𝟭 𝒞 := by
  constructor
  · have := congrArg PointedEndofunctor.F h₁
    rwa [Cyl6.mul_F, Cyl6.one_F] at this
  · have := congrArg PointedEndofunctor.F h₂
    rwa [Cyl6.mul_F, Cyl6.one_F] at this

/-- A unit's underlying endofunctor is `IsUnit` in the *functor-composition* monoid of
endofunctors `𝒞 ⥤ 𝒞` (where `1 = 𝟭`, `f * g = f ⋙ g`).  Packaged form of `strictInv_F_of_unit`. -/
theorem isUnit_F_of_isUnit {A : PointedEndofunctor 𝒞} (h : IsUnit A) :
    A.F ⋙ (h.unit⁻¹).val.F = 𝟭 𝒞 ∧ (h.unit⁻¹).val.F ⋙ A.F = 𝟭 𝒞 := by
  have hmul : A * (h.unit⁻¹).val = 1 := by
    have : h.unit.val * (h.unit⁻¹).val = 1 := by
      rw [← Units.val_mul, mul_inv_cancel, Units.val_one]
    rwa [h.unit_spec] at this
  have hmul' : (h.unit⁻¹).val * A = 1 := by
    have : (h.unit⁻¹).val * h.unit.val = 1 := by
      rw [← Units.val_mul, inv_mul_cancel, Units.val_one]
    rwa [h.unit_spec] at this
  exact strictInv_F_of_unit hmul hmul'

end Units

/-! ### Sufficiency on a groupoid base: a strict-iso `F` is a unit

On a *groupoid* base, the point obstruction vanishes — every point is automatically an iso, so a
strict isomorphism of categories `A.F` always extends to a monoid unit.  We build the inverse
pointed endofunctor explicitly: `B = ⟨G, ptB⟩` where `G` strictly inverts `A.F` and the inverse
point is forced.  Then units are detected *purely by the underlying functor*. -/

section UnitsGroupoid

variable {𝒢 : Type u} [Groupoid.{v} 𝒢]

/-- **Recognising the monoid unit.**  A pointed endofunctor `P` is `1` iff its functor is `𝟭`
(via `hF`) and its point is the canonical iso `eqToHom hF.symm : 𝟭 ⟶ P.F`.  (`1 = ⟨𝟭, 𝟙⟩` and
`𝟙 (𝟭) = eqToHom rfl`.)  This avoids the per-component `HEq` of the generic extensionality. -/
theorem eq_one_of_F_pt {P : PointedEndofunctor 𝒢} (hF : P.F = 𝟭 𝒢)
    (hpt : P.pt ≫ eqToHom hF = 𝟙 (𝟭 𝒢)) : P = 1 := by
  refine Cyl1.pointedEndofunctor_ext hF ?_
  have hpt' : P.pt = eqToHom hF.symm := by
    have := congrArg (· ≫ eqToHom hF.symm) hpt
    simpa [eqToHom_trans] using this
  rw [hpt']
  exact eqToHom_heq_id_dom _ _ hF.symm

/-- The candidate inverse point `𝟭 ⟶ G` of a strict-iso pointed endofunctor on a groupoid base,
built with **no hand naturality**: whisker the inverse `inv A.pt : A.F ⟶ 𝟭` by `G` and bridge with
the strict law `A.F ⋙ G = 𝟭`.  `eqToHom hAG.symm : 𝟭 ⟶ A.F ⋙ G`,
`whiskerRight (inv A.pt) G : A.F ⋙ G ⟶ 𝟭 ⋙ G = G`. -/
noncomputable def invPoint (A : PointedEndofunctor 𝒢) (G : 𝒢 ⥤ 𝒢) (hAG : A.F ⋙ G = 𝟭 𝒢) :
    𝟭 𝒢 ⟶ G :=
  eqToHom hAG.symm ≫ Functor.whiskerRight (inv A.pt) G

/-- **`A.F.map` agrees with `A.pt` at the next level.**  `A.pt.app (A.F.obj X) = A.F.map (A.pt.app
X)`: naturality of `A.pt` at the morphism `A.pt.app X`, cancelling the iso `A.pt.app X`. -/
theorem pt_app_F_obj (A : PointedEndofunctor 𝒢) (X : 𝒢) :
    A.pt.app (A.F.obj X) = A.F.map (A.pt.app X) := by
  have hnat := A.pt.naturality (A.pt.app X)
  simp only [Functor.id_obj, Functor.id_map] at hnat
  exact (cancel_epi (A.pt.app X)).1 hnat

/-- Component-level cancellation: `A.pt.app X ≫ invPoint.app (A.F.obj X) = eqToHom (..).symm`,
the heart of `A * B = 1`.  Uses `pt_app_F_obj` to rewrite `inv (A.pt.app (A.F X))` as `A.F.map (inv
(A.pt.app X))`, then `A.F ⋙ G = 𝟭` collapses `G.map (A.F.map ·)` to a transported identity. -/
theorem isUnit_keyAB_app (A : PointedEndofunctor 𝒢) (G : 𝒢 ⥤ 𝒢) (hAG : A.F ⋙ G = 𝟭 𝒢) (X : 𝒢) :
    A.pt.app X ≫ (invPoint A G hAG).app (A.F.obj X) = eqToHom (congrArg (·.obj X) hAG).symm := by
  rw [invPoint, NatTrans.comp_app]
  simp only [eqToHom_app, Functor.whiskerRight_app, Functor.comp_obj, Functor.id_obj]
  -- A.pt.app X ≫ eqToHom (h (A.F X)).symm ≫ G.map ((inv A.pt).app (A.F X)) = eqToHom (h X).symm
  have hinv : (inv A.pt).app (A.F.obj X) = A.F.map ((inv A.pt).app X) := by
    rw [NatIso.isIso_inv_app, NatIso.isIso_inv_app, A.F.map_inv]
    congr 1
    exact pt_app_F_obj A X
  rw [hinv]
  erw [Functor.congr_hom hAG ((inv A.pt).app X)]
  simp only [Functor.id_map, Functor.id_obj, NatIso.isIso_inv_app]
  -- A.pt.app X ≫ eqToHom .. ≫ eqToHom .. ≫ inv (A.pt.app X) ≫ eqToHom .. = eqToHom ..
  simp [IsIso.hom_inv_id_assoc]

/-- **`A * B = 1` for the candidate inverse**, packaged as a pointed-endofunctor equation, for ANY
`A` with a strict right-inverse `G`.  `B = ⟨G, invPoint A G hAG⟩`.  Proven via `isUnit_keyAB_app`
(component-level) and `eq_one_of_F_pt`. -/
theorem mul_invPointObj_eq_one (A : PointedEndofunctor 𝒢) (G : 𝒢 ⥤ 𝒢) (hAG : A.F ⋙ G = 𝟭 𝒢) :
    A * (⟨G, invPoint A G hAG⟩ : PointedEndofunctor 𝒢) = 1 := by
  refine eq_one_of_F_pt (P := A * ⟨G, invPoint A G hAG⟩) (show A.F ⋙ G = 𝟭 𝒢 from hAG) ?_
  ext X
  simp only [NatTrans.comp_app, eqToHom_app, NatTrans.id_app, Functor.id_obj]
  rw [Cyl6.mul_pt_app]
  change (A.pt.app X ≫ (invPoint A G hAG).app (A.F.obj X)) ≫ eqToHom _ = 𝟙 X
  rw [isUnit_keyAB_app A G hAG X]
  simp [eqToHom_trans]

/-- **A strict-iso `F` extends to a monoid unit on a groupoid base.**  Given `A : PointedEndofunctor
𝒢` whose underlying functor has a strict inverse `G` (`A.F ⋙ G = 𝟭`, `G ⋙ A.F = 𝟭`), the element
`A` is a unit.  We get the left product `A * B = 1` and the right product `B * B' = 1` both from
`mul_invPointObj_eq_one` (applied to `A` resp. to `B`); the monoid identity `A = 1 * A = (B' *
B) * A`-style argument (`left_inv_eq_right_inv`) then makes `B` a two-sided inverse of `A`.

**Status: PROVEN.** -/
theorem isUnit_of_strictInv (A : PointedEndofunctor 𝒢) (G : 𝒢 ⥤ 𝒢)
    (hAG : A.F ⋙ G = 𝟭 𝒢) (hGA : G ⋙ A.F = 𝟭 𝒢) : IsUnit A := by
  set B : PointedEndofunctor 𝒢 := ⟨G, invPoint A G hAG⟩ with hBdef
  -- A is a left inverse of B (A * B = 1).
  have hAB : A * B = 1 := mul_invPointObj_eq_one A G hAG
  -- B has a right inverse B' (B * B' = 1), since B.F = G also strictly inverts A.F via hGA.
  have hBB' : B * (⟨A.F, invPoint B A.F hGA⟩ : PointedEndofunctor 𝒢) = 1 :=
    mul_invPointObj_eq_one B A.F hGA
  -- A left-inverse and a right-inverse of B coincide, so A is a two-sided inverse of B.
  have hBA : B * A = 1 := by
    have : A = (⟨A.F, invPoint B A.F hGA⟩ : PointedEndofunctor 𝒢) :=
      left_inv_eq_right_inv hAB hBB'
    rw [this]; exact hBB'
  exact ⟨⟨A, B, hAB, hBA⟩, rfl⟩

end UnitsGroupoid

/-! ### The maximal subgroup (group of units) and the headline non-group witness

Mathlib's `IsUnit.submonoid M` is the submonoid of units, carrying a `Group` instance — this is the
**maximal subgroup** of `M`.  We record `1 ∈` it, and the headline negative result: `M` is **not** a
group, because an endofunctor with non-injective object map is never a unit. -/

section MaximalSubgroup

variable {𝒞 : Type u} [Category.{v} 𝒞]

/-- **The maximal subgroup of `M` is `IsUnit.submonoid`** (mathlib `Group` instance).  This is the
group of units / "loop cylinders" abstractly. -/
abbrev unitsSubgroup (𝒞 : Type u) [Category.{v} 𝒞] : Submonoid (PointedEndofunctor 𝒞) :=
  IsUnit.submonoid (PointedEndofunctor 𝒞)

/-- `1` is a unit (in the group of units). -/
theorem one_isUnit : IsUnit (1 : PointedEndofunctor 𝒞) := isUnit_one

/-- A unit's object map has a *left inverse on objects*, hence is **injective on objects**. -/
theorem objMap_injective_of_isUnit {A : PointedEndofunctor 𝒞} (h : IsUnit A) :
    Function.Injective A.F.obj := by
  obtain ⟨hAG, _⟩ := isUnit_F_of_isUnit h
  have hleft : ∀ z, (h.unit⁻¹).val.F.obj (A.F.obj z) = z := fun z => congrArg (·.obj z) hAG
  intro x y hxy
  calc x = (h.unit⁻¹).val.F.obj (A.F.obj x) := (hleft x).symm
    _ = (h.unit⁻¹).val.F.obj (A.F.obj y) := by rw [hxy]
    _ = y := hleft y

/-- **A pointed endofunctor with non-injective object map is NOT a unit.**  The contrapositive of
`objMap_injective_of_isUnit`: such an `A.F` cannot be a strict iso of categories. -/
theorem not_isUnit_of_objMap_not_injective {A : PointedEndofunctor 𝒞}
    (h : ¬ Function.Injective A.F.obj) : ¬ IsUnit A :=
  fun hu => h (objMap_injective_of_isUnit hu)

end MaximalSubgroup

/-! ### The monoid is NOT a group (concrete free-groupoid witness)

A free groupoid on a type with ≥ 2 objects carries a *constant* object-map endofunctor, whose object
map is non-injective, hence a non-unit.  So `M` is genuinely a monoid, not a group. -/

section NotGroup

variable {C : Type u} [Category.{v} C]

/-- **The constant-object cylinder element.**  `pointedOfPaths (fun _ => of x₀) (η)` for a fixed
basepoint `x₀` and the canonical paths `η x : of x ⟶ of x₀`.  Its underlying functor sends every
generator to `of x₀`, so the object map is constant. -/
noncomputable def constObj (x₀ : C)
    (η : ∀ x, (FreeGroupoid.of C).obj x ⟶ (FreeGroupoid.of C).obj x₀) :
    PointedEndofunctor (FreeGroupoid C) :=
  pointedOfPaths (fun _ => (FreeGroupoid.of C).obj x₀) η

/-- The object map of `constObj` is the constant map `_ ↦ of x₀`. -/
@[simp] theorem constObj_F_obj (x₀ : C)
    (η : ∀ x, (FreeGroupoid.of C).obj x ⟶ (FreeGroupoid.of C).obj x₀) (x : C) :
    (constObj x₀ η).F.obj ((FreeGroupoid.of C).obj x) = (FreeGroupoid.of C).obj x₀ := rfl

/-- **`constObj` is NOT a unit** when there exist two generators with distinct images — its object
map is non-injective (`of x₀` is hit by all generators).  Hence `M = PointedEndofunctor
(FreeGroupoid C)` is **not a group** whenever `C` has two objects with distinct images. -/
theorem constObj_not_isUnit (x₀ x₁ : C)
    (η : ∀ x, (FreeGroupoid.of C).obj x ⟶ (FreeGroupoid.of C).obj x₀)
    (hne : (FreeGroupoid.of C).obj x₀ ≠ (FreeGroupoid.of C).obj x₁) :
    ¬ IsUnit (constObj x₀ η) := by
  apply not_isUnit_of_objMap_not_injective
  intro hinj
  -- A.F.obj (of x₀) = of x₀ = A.F.obj (of x₁), so injectivity forces of x₀ = of x₁.
  apply hne
  apply hinj
  rw [constObj_F_obj, constObj_F_obj]

end NotGroup

/-! ## 2. Idempotents

`IsIdempotentElem A` is `A * A = A` (mathlib).  Two structural facts:

* **Every idempotent UNIT is `1`** (mathlib `IsIdempotentElem.iff_eq_one_of_isUnit`): in the group
  of units the only idempotent is the identity.
* **Nontrivial idempotents EXIST** in `M = PointedEndofunctor (FreeGroupoid C)`: the constant-object
  endofunctor `constObj x₀ η` with `η x₀ = 𝟙` is idempotent (`A.F ⋙ A.F = A.F` because the constant
  functor absorbs composition, and the point condition holds at the single image object `of x₀`),
  yet `≠ 1` (its `F` is constant, not `𝟭`).  This is an idempotent-monad-like "collapse to a point".
-/

section Idempotents

variable {𝒞 : Type u} [Category.{v} 𝒞]

/-- **Idempotent ⟹ `F` is idempotent under composition.**  `A * A = A` projects on the `F` field to
`A.F ⋙ A.F = A.F`. -/
theorem comp_F_self_of_idempotent {A : PointedEndofunctor 𝒞} (h : IsIdempotentElem A) :
    A.F ⋙ A.F = A.F := by
  have := congrArg PointedEndofunctor.F h.eq
  rwa [Cyl6.mul_F] at this

/-- **Every idempotent unit is `1`** (mathlib).  In the group of units `IsUnit.submonoid M`, the
only idempotent is the identity `1`. -/
theorem idempotent_unit_eq_one {A : PointedEndofunctor 𝒞} (hu : IsUnit A)
    (hi : IsIdempotentElem A) : A = 1 :=
  (IsIdempotentElem.iff_eq_one_of_isUnit hu).1 hi

end Idempotents

/-! ### Nontrivial idempotents exist: the constant-object collapse

`constObj x₀ η` (object map constant at `of x₀`) is idempotent iff its single self-path `η x₀` is
the identity.  Such an idempotent is `≠ 1`. -/

section IdempotentWitness

variable {C : Type u} [Category.{v} C]

/-- **The constant-object endofunctor is idempotent when `η x₀ = 𝟙`.**  Its underlying functor is
constant at `of x₀`, so `A.F ⋙ A.F = A.F` (the constant absorbs composition); and the product point
at a generator `x` is `η x ≫ pt.app (of x₀) = η x ≫ η x₀ = η x` once `η x₀ = 𝟙`. -/
theorem constObj_isIdempotent (x₀ : C)
    (η : ∀ x, (FreeGroupoid.of C).obj x ⟶ (FreeGroupoid.of C).obj x₀)
    (hη : η x₀ = 𝟙 ((FreeGroupoid.of C).obj x₀)) :
    IsIdempotentElem (constObj x₀ η) := by
  rw [IsIdempotentElem, constObj]
  set F₀ : C → FreeGroupoid C := fun _ => (FreeGroupoid.of C).obj x₀ with hF₀
  set A : PointedEndofunctor (FreeGroupoid C) := pointedOfPaths F₀ η with hA
  -- The product is `objDataEquiv` of its own data (Cyl1 converse); `A` is `objDataEquiv ⟨F₀, η⟩`.
  -- Show the two object-data agree as a `Sigma`, then `congrArg objDataEquiv`.
  -- The product's path family equals `η` (`Cyl6` product formula + `η x₀ = 𝟙`), and its object map
  -- equals `F₀`.  Use `Cyl6.mul_pointedOfPaths_*` (which `A * A` matches, definitionally).
  have hp : ∀ x, Cyl1.pathMap
      (pointedOfPaths F₀ η * pointedOfPaths F₀ η) x = η x := fun x => by
    rw [Cyl6.mul_pointedOfPaths_pathMap, Cyl1.pointedOfPaths_pt_app_mk, hη]
    exact Category.comp_id _
  have hobj : Cyl1.objMap (pointedOfPaths F₀ η * pointedOfPaths F₀ η) = F₀ := by
    funext x; rw [Cyl6.mul_pointedOfPaths_objMap]; rfl
  -- `A*A = objDataEquiv ⟨objMap,pathMap⟩`, `A = objDataEquiv ⟨F₀,η⟩`; reduce to the data equality.
  have hheq : HEq (Cyl1.pathMap (pointedOfPaths F₀ η * pointedOfPaths F₀ η)) η := by
    rw [funext hp]  -- reduces to `η ≍ η`
    rfl
  have hdata : (⟨Cyl1.objMap (pointedOfPaths F₀ η * pointedOfPaths F₀ η),
      Cyl1.pathMap (pointedOfPaths F₀ η * pointedOfPaths F₀ η)⟩ : Cyl1.ObjData C) = ⟨F₀, η⟩ :=
    Sigma.ext hobj hheq
  calc A * A = Cyl1.objDataEquiv ⟨Cyl1.objMap (A * A), Cyl1.pathMap (A * A)⟩ :=
        (Cyl1.pointedOfPaths_objData (A * A)).symm
    _ = Cyl1.objDataEquiv ⟨F₀, η⟩ := congrArg _ hdata
    _ = A := rfl

/-- **There IS a nontrivial idempotent** (`≠ 1`).  Given a basepoint `x₀`, a self-trivial path
family `η` (with `η x₀ = 𝟙` — this requires `x₀` to receive a path from every generator, e.g. `C`
connected), and a generator `x₁` with `of x₁ ≠ of x₀`, the constant-object endofunctor `constObj x₀
η` is idempotent (`constObj_isIdempotent`) and `≠ 1` (its `F` is constant at `of x₀`, not `𝟭`).

So the monoid `PointedEndofunctor (FreeGroupoid C)` has **nontrivial idempotents** — idempotent
endofunctors that collapse the groupoid onto a single object (an "idempotent-monad-like"
retraction), genuinely different from the unit `1`.  (The point being iso forces this collapse to
be *up to iso* the identity, but the underlying endofunctor is strictly constant, not `𝟭`.) -/
theorem exists_nontrivial_idempotent (x₀ x₁ : C)
    (η : ∀ x, (FreeGroupoid.of C).obj x ⟶ (FreeGroupoid.of C).obj x₀)
    (hη : η x₀ = 𝟙 ((FreeGroupoid.of C).obj x₀))
    (hne : (FreeGroupoid.of C).obj x₁ ≠ (FreeGroupoid.of C).obj x₀) :
    ∃ A : PointedEndofunctor (FreeGroupoid C), IsIdempotentElem A ∧ A ≠ 1 := by
  refine ⟨constObj x₀ η, constObj_isIdempotent x₀ η hη, ?_⟩
  intro hone
  -- A = 1 ⟹ A.F = 𝟭 ⟹ A.F.obj (of x₁) = of x₁, but constObj gives of x₀.
  apply hne
  have hF : (constObj x₀ η).F = (1 : PointedEndofunctor (FreeGroupoid C)).F :=
    congrArg PointedEndofunctor.F hone
  have := congrArg (·.obj ((FreeGroupoid.of C).obj x₁)) hF
  simpa [constObj_F_obj] using this.symm

end IdempotentWitness

/-! ## 3. Well-pointedness — SETTLED (Cyl1's flagged open question)

Cyl1 isolated `isWellPointed_iff`: `pointedOfPaths F₀ η` is well-pointed (Kelly, `F ◫ pt = pt ◫ F`)
iff `∀ x, F.map (η x) = pt.app (F₀ x)`, and flagged the cylinder's `(Rgrpd∘Lgrpd⁻¹, counit≫sweepR)`
as the open "one surviving non-degenerate invariant".

**Verdict: every pointed endofunctor of a groupoid is well-pointed — so the cylinder ones ARE.**
The reason is exactly `pt_app_F_obj`: in a groupoid the point is iso, and naturality of `A.pt` at
the morphism `A.pt.app X` forces `A.pt.app (A.F.obj X) = A.F.map (A.pt.app X)`, which at a generator
`X = of x` *is* the Kelly equation `pt.app (F₀ x) = F.map (η x)`.  So well-pointedness is **free**
here, not a discriminating invariant. -/

section WellPointed

variable {𝒢 : Type u} [Groupoid.{v} 𝒢]

/-- **Every pointed endofunctor of a groupoid is well-pointed.**  `F.map (pt.app Z) = pt.app (F.obj
Z)` for all `Z`: this is `pt_app_F_obj` (naturality of the iso point), so Kelly's well-pointedness
is *automatic* in a groupoid base. -/
theorem isWellPointed_of_groupoid (A : PointedEndofunctor 𝒢) (Z : 𝒢) :
    A.F.map (A.pt.app Z) = A.pt.app (A.F.obj Z) :=
  (pt_app_F_obj A Z).symm

end WellPointed

section WellPointedFree

variable {C : Type u} [Category.{v} C]

/-- **The cylinder's `(F₀, η)` is well-pointed** (Cyl1's open question, answered YES).  Any
`pointedOfPaths F₀ η` — in particular the cylinder construction `cylToPointedObj` with `F₀ =
Rgrpd∘Lgrpd⁻¹`, `η = counit≫sweepR` — satisfies the Kelly equation `F.map (η x) = pt.app (F₀ x)` for
every generator `x`.  Hence well-pointedness does **not** distinguish cylinders at this layer; it is
automatic because the base `FreeGroupoid C` is a groupoid (`isWellPointed_of_groupoid`). -/
theorem pointedOfPaths_isWellPointed (F₀ : C → FreeGroupoid C)
    (η : ∀ x, (FreeGroupoid.of C).obj x ⟶ F₀ x) :
    Cyl1.IsWellPointed (pointedOfPaths F₀ η) :=
  fun Z => isWellPointed_of_groupoid (pointedOfPaths F₀ η) Z

end WellPointedFree

/-! ## 4. Commutativity and generation

* **Non-commutative.** The product object map STACKS (`Cyl6.mul_objMap`: `objMap (A*B) x = B.F.obj
  (A.F.obj (of x))`), so `A * B` and `B * A` generally differ.  We exhibit a concrete pair.
* **Generation.** `mooreSubmonoid K` is generated by the **elementary** (length-1, single-`□¹`)
  cylinders — this is exactly `Cyl8.mooreSubmonoid_eq_closure`, re-exported. -/

section Commutativity

variable {C : Type u} [Category.{v} C]

/-- **The monoid is non-commutative in general.**  Concretely: a constant-object factor and a
non-constant one do not commute, because the product object map stacks.  We state the clean
witness — there exist `A B` with `A * B ≠ B * A` — given two generators `x₀ ≠ x₁` (distinct images)
and a constant collapse `constObj x₀ η`: `constObj * A` collapses everything to `of x₀`, while
`A * constObj` need not, so their object maps differ. -/
theorem not_commutative_witness (x₀ x₁ : C)
    (η : ∀ x, (FreeGroupoid.of C).obj x ⟶ (FreeGroupoid.of C).obj x₀)
    (θ : ∀ x, (FreeGroupoid.of C).obj x ⟶ (FreeGroupoid.of C).obj x₁)
    (hne : (FreeGroupoid.of C).obj x₀ ≠ (FreeGroupoid.of C).obj x₁) :
    constObj x₀ η * constObj x₁ θ ≠ constObj x₁ θ * constObj x₀ η := by
  intro h
  -- objMap (constObj x₀ η * constObj x₁ θ) x = (constObj x₁ θ).F.obj (of x₀) = of x₁
  -- objMap (constObj x₁ θ * constObj x₀ η) x = (constObj x₀ η).F.obj (of x₁) = of x₀
  -- equal ⟹ of x₁ = of x₀, contradiction.
  have hobj := congrArg (fun P => Cyl1.objMap P x₀) h
  simp only [Cyl6.mul_objMap, constObj] at hobj
  -- (pointedOfPaths …).F.obj ((pointedOfPaths …).F.obj (of x₀)) on each side
  rw [show (pointedOfPaths (fun _ => (FreeGroupoid.of C).obj x₁) θ).F.obj
        ((pointedOfPaths (fun _ => (FreeGroupoid.of C).obj x₀) η).F.obj
          ((FreeGroupoid.of C).obj x₀)) = (FreeGroupoid.of C).obj x₁ from rfl,
    show (pointedOfPaths (fun _ => (FreeGroupoid.of C).obj x₀) η).F.obj
        ((pointedOfPaths (fun _ => (FreeGroupoid.of C).obj x₁) θ).F.obj
          ((FreeGroupoid.of C).obj x₀)) = (FreeGroupoid.of C).obj x₀ from rfl] at hobj
  exact hne hobj.symm

end Commutativity

section Generation

variable {K : BPSet}

/-- **`mooreSubmonoid K` is generated by the ELEMENTARY (length-1) cylinders.**  Re-export of
`Cyl8.mooreSubmonoid_eq_closure`: the submonoid generated by the strict `□¹` cylinder image
`cylImage K` (each a single elementary cylinder) is exactly `mooreSubmonoid K`.  So the elementary
cylinders generate, and the (Moore) submonoid is their `Submonoid.closure`. -/
theorem mooreSubmonoid_generated_by_elementary :
    Cyl8.mooreSubmonoid K = Submonoid.closure (Cyl6.cylImage K) :=
  Cyl8.mooreSubmonoid_eq_closure

/-- **Concatenation realises the product on `mooreSubmonoid`** (re-export of
`Cyl8.mooreToPointed_concat`): the generation is by list-concatenation of elementary cylinders, the
monoid product.  So every element of `mooreSubmonoid K` is a product of elementary generators. -/
theorem moore_product_is_concatenation (m m' : Cyl8.MooreList K) :
    Cyl8.mooreToPointed (m.concat m') = Cyl8.mooreToPointed m * Cyl8.mooreToPointed m' :=
  Cyl8.mooreToPointed_concat m m'

end Generation

end Cyl13
