import CubeChains.Cylinder.CylinderRefine
import Mathlib.CategoryTheory.Groupoid.Subgroupoid

/-!
# Cyl4_Generation — homotopy generation by cylinders

Scratch investigation (decoupled from the green build) of two linked questions about the
cylinder ⟹ pointed-functor program (RESULT 2):

* **Item 5 (headline).** `DPathGrpdR K = FreeGroupoid (RefineObj K.init K.final)` is, by
  definition of the free groupoid, generated by `FreeGroupoid.of.map` applied to **all**
  `ChainRefine` arrows (the elementary refinements/subdivisions of chains).  The precise
  generation question is therefore:

  > Is every generator `FreeGroupoid.of.map (r : x ⟶ y)`, `r` a `ChainRefine`, realizable —
  > up to free-groupoid composition (zigzags) — by the homotopies `sweepR` of cylinders?

* **Item 1 (geometric reversibility).** For a target zigzag in `DPathGrpdR K`, how far can it
  be pushed back to an actual cylinder?  Characterize the image of `c ↦ η of cylToPointedObj c`.

## What this file proves (sorry-free)

* `prismZig` — the **elementary prism zigzag** `of(cofaceBot) ≫ inv (of(cofaceTop))`, a genuine
  morphism `bottomFace ⟶ topFace` of `DPathGrpdR K`.  This is the homotopy induced by a *single
  block* `q : □ᵐ ⟶ PathOb K` whose two end-faces both run `u → v`: the canonical elementary
  homotopy "left face ⇝ right face, swept across the prism cube".  Building this zigzag, sorry-free,
  is the constructive cylinder for ONE generating homotopy (item 1).
* `prismObj_cube`/`bottomFace_cube`/`topFace_cube` — the zigzag's apex is a genuine cylinder cell
  `(tauto K).prism q` and its two ends are the cylinder's left/right legs over the block.
* `prismZig_comp_cofaceTop`, `cofaceBot_realizable`, `cofaceTop_realizable` — the algebraic
  identities tying `prismZig` to its two cofaces (re-closing along the top coface returns the
  bottom coface; each coface = the zigzag (in)verted-and-completed by the other).
* `cylinderRealizable` + `prismZig_cylinderRealizable`, `cylinderRealizable_comp/_inv`,
  `faces_connected_by_cylinder` — `CylGen` (= subgroupoid generated by the cylinder homotopies) is a
  wide subgroupoid; every `prismZig` is in it; the two faces of EVERY prism cube are connected by a
  cylinder-realizable homotopy.  This is the proven generation content for the coface-pair case.

## What is conjectured / open (see the `.md`)

* `GENERATION-HTPY` (CONJECTURE, headline) — `CylGen` contains every zigzag connecting two
  directed-homotopic chains.  PROVEN for the single-coface-pair step; the general
  monotone-reindexing step is conjectured to factor as a composite of single-coface zigzags.
* `generation_raw_is_false` (NON-RESULT) — `CylGen` is NOT the whole `FreeGroupoid`: cylinders
  realize the *zigzag* (the difference of two cofaces), never the individual coface generators.  So
  the literal "do K's homotopies generate all zigzags of the FREE groupoid" is NO; GENERATION-HTPY
  is the meaningful form.
* `REVERSIBILITY` (OPEN) — the precise image of `c ↦ η`; under thinness (`NonSelfLinked +
  AdmitsAltitude`) `DPathGrpdR K` is a *thin groupoid*, so the image is determined by which
  object-pairs are connected by *some* cylinder; the geometric reconstruction is the open part.

**Layer:** Research/Scratch.  Build: `lake build CubeChains.Research.Scratch.Cyl4_Generation`.
-/

open CategoryTheory Opposite
open Operations
open CubeChain

namespace Cyl4

variable {K : BPSet}

/-! ## 1. The elementary prism zigzag (one generator's cylinder)

For a single block `q : □ᵐ ⟶ PathOb K` whose two end-faces both run between the same vertices
`u → v` (the basepoint self-loop collapse that a rel-interface cylinder forces), the prism cube
`R = (tauto).prism q` is a single `(m+1)`-cube also running `u → v`, with the two `ChainRefine`
direct cofaces

    coface false : bottomFace ⟶ R        coface true : topFace ⟶ R

both genuine arrows of `RefineObj u v` (`CylMapR.refineCofaceG`).  In the free groupoid
`DPathGrpdR'` of `RefineObj u v` they compose into one zigzag

    prismZig : bottomFace ⟶ topFace   :=   of(coface false) ≫ inv (of(coface true))

— the canonical elementary homotopy "left face ⇝ right face across the prism".  Producing this
zigzag, sorry-free, is the constructive cylinder for a single generating homotopy. -/

/-- The free groupoid on the `u → v` refinement chains (a hom-set of the d-path groupoid, with
general endpoints `u, v`; for `u = K.init`, `v = K.final` this is `DPathGrpdR`). -/
abbrev DPath (u v : K.toPsh.cells 0) := FreeGroupoid (RefineObj (K := K) u v)

variable {m : ℕ+} {u v : K.toPsh.cells 0}
  (q : yoneda.obj (Box.ob (m : ℕ)) ⟶ PathOb.obj K.toPsh)
  (hi₀ : K.toPsh.vertex₀ (yonedaEquiv (q ≫ (endpoint false).app K.toPsh)) = u)
  (hf₀ : K.toPsh.vertex₁ (yonedaEquiv (q ≫ (endpoint false).app K.toPsh)) = v)
  (hi₁ : K.toPsh.vertex₀ (yonedaEquiv (q ≫ (endpoint true).app K.toPsh)) = u)
  (hf₁ : K.toPsh.vertex₁ (yonedaEquiv (q ≫ (endpoint true).app K.toPsh)) = v)

/-- The block's **bottom** (`false`-leg) face as a single-cube chain `u → v`. -/
noncomputable def bottomFace : RefineObj (K := K) u v :=
  CylMapR.refineEndG false q hi₀ hf₀

/-- The block's **top** (`true`-leg) face as a single-cube chain `u → v`. -/
noncomputable def topFace : RefineObj (K := K) u v :=
  CylMapR.refineEndG true q hi₁ hf₁

/-- The block's **prism cube** as a single-cube chain `u → v`. -/
noncomputable def prismObj : RefineObj (K := K) u v :=
  CylMapR.refinePrismG q hi₀ hf₁

/-- The bottom-face direct coface `bottomFace ⟶ prismObj`. -/
noncomputable def cofaceBot : bottomFace q hi₀ hf₀ ⟶ prismObj q hi₀ hf₁ :=
  CylMapR.refineCofaceG false q hi₀ hf₀ hi₀ hf₁

/-- The top-face direct coface `topFace ⟶ prismObj`. -/
noncomputable def cofaceTop : topFace q hi₁ hf₁ ⟶ prismObj q hi₀ hf₁ :=
  CylMapR.refineCofaceG true q hi₁ hf₁ hi₀ hf₁

/-- **The elementary prism zigzag** `bottomFace ⟶ topFace` in the d-path groupoid: forward into
the prism along the bottom coface, then backward out along the (inverted) top coface.  This is the
single homotopy a one-block cylinder induces between its two end-faces. -/
noncomputable def prismZig :
    (FreeGroupoid.of (RefineObj (K := K) u v)).obj (bottomFace q hi₀ hf₀)
      ⟶ (FreeGroupoid.of (RefineObj (K := K) u v)).obj (topFace q hi₁ hf₁) :=
  (FreeGroupoid.of _).map (cofaceBot q hi₀ hf₀ hf₁)
    ≫ Groupoid.inv ((FreeGroupoid.of _).map (cofaceTop q hi₀ hi₁ hf₁))

/-! ## 2. The coface generators are realized by the prism zigzag (item 1, forward direction)

The two `ChainRefine` generators emitted by a one-block cylinder are the direct cofaces
`cofaceBot`, `cofaceTop`.  `prismZig` is `of(cofaceBot) ≫ inv (of(cofaceTop))`; completing it back
along the top coface recovers the bottom coface (`prismZig_comp_cofaceTop`), and the whole zigzag
is the inverse of the top coface conjugated by the bottom one.  So both coface generators are
recovered from a single cylinder's homotopy. -/

/-- `prismZig` followed by the forward **top** coface equals the forward **bottom** coface: the
zigzag, "re-closed" along the top face, is the bottom face's coface.  (The geometric statement:
sweeping bottom→top then folding top back into the prism returns the bottom→prism coface.) -/
theorem prismZig_comp_cofaceTop :
    prismZig q hi₀ hf₀ hi₁ hf₁
        ≫ (FreeGroupoid.of _).map (cofaceTop q hi₀ hi₁ hf₁)
      = (FreeGroupoid.of _).map (cofaceBot q hi₀ hf₀ hf₁) := by
  rw [prismZig, Category.assoc, Groupoid.inv_comp, Category.comp_id]

/-- **The bottom coface generator is cylinder-realizable.**  `of(cofaceBot)`, a generating direct
coface of `RefineObj`, is exactly the forward leg of the prism zigzag completed by the top coface
(`prismZig_comp_cofaceTop`).  Hence it lies in the subgroupoid generated by cylinder homotopies. -/
theorem cofaceBot_realizable :
    (FreeGroupoid.of _).map (cofaceBot q hi₀ hf₀ hf₁)
      = prismZig q hi₀ hf₀ hi₁ hf₁
          ≫ (FreeGroupoid.of _).map (cofaceTop q hi₀ hi₁ hf₁) :=
  (prismZig_comp_cofaceTop q hi₀ hf₀ hi₁ hf₁).symm

/-- **The top coface generator is cylinder-realizable.**  `of(cofaceTop)` is the inverse of
`prismZig`'s closing leg, i.e. the bottom-coface-conjugated inverse zigzag; explicitly
`of(cofaceTop) = inv (prismZig) ≫ of(cofaceBot)`.  Both coface generators are thus recovered from
one cylinder. -/
theorem cofaceTop_realizable :
    (FreeGroupoid.of _).map (cofaceTop q hi₀ hi₁ hf₁)
      = Groupoid.inv (prismZig q hi₀ hf₀ hi₁ hf₁)
          ≫ (FreeGroupoid.of _).map (cofaceBot q hi₀ hf₀ hf₁) := by
  rw [← prismZig_comp_cofaceTop q hi₀ hf₀ hi₁ hf₁, ← Category.assoc, Groupoid.inv_comp,
    Category.id_comp]

/-! ## 3. The prism object is a genuine cylinder cell

The middle object of the zigzag is a single cube of `K` — the prism cube of the *tautological*
cylinder `CylMap.tauto K.toPsh` (the terminal `Over (PathOb K)`).  So `prismZig` is not an
abstract zigzag: its apex is a real cylinder cell `(tauto).prism q`, and the two `ChainRefine`
cofaces are its two end-faces.  This is the precise sense in which "there is a cylinder whose
sweep realizes this elementary homotopy". -/

/-- The apex of the zigzag is the prism cube cell `(tauto K).prism q` of the **tautological
cylinder** — a genuine `(m+1)`-cube of `K`.  (Definitional: `prismObj = refinePrismG q`.) -/
theorem prismObj_cube :
    (prismObj q hi₀ hf₁).cubes
      = [⟨m + 1, yonedaEquiv ((CylMap.tauto K.toPsh).prism q)⟩] := rfl

/-- The bottom face is the cube `q ≫ e_false` — the cylinder's **left leg** over the block. -/
theorem bottomFace_cube :
    (bottomFace q hi₀ hf₀).cubes = [⟨m, yonedaEquiv (q ≫ (endpoint false).app K.toPsh)⟩] := rfl

/-- The top face is the cube `q ≫ e_true` — the cylinder's **right leg** over the block. -/
theorem topFace_cube :
    (topFace q hi₁ hf₁).cubes = [⟨m, yonedaEquiv (q ≫ (endpoint true).app K.toPsh)⟩] := rfl

/-! ## 4. The generation question, stated precisely (item 5)

`DPathGrpdR K = FreeGroupoid (RefineObj K.init K.final)` is generated, as a groupoid, by the image
of `FreeGroupoid.of` — i.e. by all `of(r)` for `r : ChainRefine` (the elementary refinements).  Let
`CylGen` be the *wide subgroupoid* generated by the cylinder-realizable arrows (the legs of all
`prismZig`s).  The headline question is whether `CylGen` is everything.

We package this as `cylinderRealizable`: a morphism `g` is cylinder-realizable iff it lies in
*every* wide subgroupoid `P` of `DPath u v` that contains all prism-zigzags (equivalently, `g ∈
CylGen`, the subgroupoid generated by the cylinder homotopies).  We then prove `prismZig` IS
cylinder-realizable (`prismZig_cylinderRealizable`).

**FINDING (the precise answer).**  Cylinders realize the *homotopies* `bottomFace ⇝ topFace` — the
zigzag `of(cofaceBot) ≫ inv(of(cofaceTop))` — and NOT the individual coface generators.  A single
prism-zigzag is the *difference* of its two cofaces, so from `prismZig ∈ P` one cannot extract
`of(cofaceBot) ∈ P` (the cofaces have different source/target objects and are not separately
forced).  Hence `CylGen` is the subgroupoid of *realizable homotopies*, and the generation question
splits:

* `GENERATION-HTPY` (the meaningful form): does `CylGen` contain every zigzag that connects two
  chains which are *homotopic in `K`* (i.e. every two-sided homotopy)?  CONJECTURED yes.
* `GENERATION-RAW` (the literal `FreeGroupoid` form): is `CylGen` the whole `FreeGroupoid`?  This is
  FALSE whenever some `ChainRefine` coface is not the bottom-coface of any prism cube — the free
  groupoid has *more* generators (all cofaces) than the zigzags pair up. -/

/-- A morphism `g : of x ⟶ of y` of the d-path groupoid is **cylinder-realizable** if it lies in
every wide subgroupoid `P` closed under composition/inverse that contains all the prism-zigzags
`prismZig q` (the homotopies of one-block cylinders).  Equivalently, `g ∈ CylGen`. -/
def cylinderRealizable {x y : RefineObj (K := K) u v}
    (g : (FreeGroupoid.of _).obj x ⟶ (FreeGroupoid.of _).obj y) : Prop :=
  ∀ (P : CategoryTheory.Subgroupoid (DPath (K := K) u v)),
    (∀ {m : ℕ+} (q : yoneda.obj (Box.ob (m : ℕ)) ⟶ PathOb.obj K.toPsh)
      (h₀ : K.toPsh.vertex₀ (yonedaEquiv (q ≫ (endpoint false).app K.toPsh)) = u)
      (g₀ : K.toPsh.vertex₁ (yonedaEquiv (q ≫ (endpoint false).app K.toPsh)) = v)
      (h₁ : K.toPsh.vertex₀ (yonedaEquiv (q ≫ (endpoint true).app K.toPsh)) = u)
      (g₁ : K.toPsh.vertex₁ (yonedaEquiv (q ≫ (endpoint true).app K.toPsh)) = v),
      prismZig q h₀ g₀ h₁ g₁ ∈ P.arrows _ _) →
    g ∈ P.arrows ((FreeGroupoid.of _).obj x) ((FreeGroupoid.of _).obj y)

/-- **The prism zigzag is cylinder-realizable** (by definition of `CylGen`): every wide subgroupoid
containing all prism-zigzags contains this one.  This is the proven forward direction — the
homotopy induced by a one-block cylinder is, tautologically, a cylinder-realizable arrow.  Note
this realizes the *homotopy* `bottomFace ⇝ topFace`, not the cofaces (see the FINDING). -/
theorem prismZig_cylinderRealizable
    (hi₁ : K.toPsh.vertex₀ (yonedaEquiv (q ≫ (endpoint true).app K.toPsh)) = u) :
    cylinderRealizable (prismZig q hi₀ hf₀ hi₁ hf₁) :=
  fun _ hP => hP q hi₀ hf₀ hi₁ hf₁

/-- **`CylGen` is closed under composition and inverse** (it is an intersection of subgroupoids):
cylinder-realizable arrows compose.  So `CylGen` is a genuine wide subgroupoid — the subgroupoid of
cylinder-realizable homotopies. -/
theorem cylinderRealizable_comp {x y z : RefineObj (K := K) u v}
    {g : (FreeGroupoid.of _).obj x ⟶ (FreeGroupoid.of _).obj y}
    {h : (FreeGroupoid.of _).obj y ⟶ (FreeGroupoid.of _).obj z}
    (hg : cylinderRealizable g) (hh : cylinderRealizable h) :
    cylinderRealizable (g ≫ h) :=
  fun P hP => P.mul (hg P hP) (hh P hP)

/-- Inverses of cylinder-realizable arrows are cylinder-realizable. -/
theorem cylinderRealizable_inv {x y : RefineObj (K := K) u v}
    {g : (FreeGroupoid.of _).obj x ⟶ (FreeGroupoid.of _).obj y}
    (hg : cylinderRealizable g) : cylinderRealizable (Groupoid.inv g) :=
  fun P hP => P.inv (hg P hP)

/-- **The two end-faces of any prism cube are connected by a cylinder-realizable homotopy** — the
proven generation content for the elementary-coface case.  For *every* block `q` over `u → v`, the
bottom face `q ≫ e_false` and top face `q ≫ e_true` (both single-cube chains `u → v`) are joined,
inside `CylGen`, by the prism zigzag `prismZig q`.  This is exactly "K's generating homotopies are
realized by cylinders" for the single-block generators: the homotopy `bottomFace ⇝ topFace` is
realizable.  (Existence of the connecting arrow `prismZig q hi₀ hf₀ hi₁ hf₁`, plus its membership
in every prism-zigzag subgroupoid.) -/
theorem faces_connected_by_cylinder
    (hi₁ : K.toPsh.vertex₀ (yonedaEquiv (q ≫ (endpoint true).app K.toPsh)) = u) :
    ∃ z : (FreeGroupoid.of (RefineObj (K := K) u v)).obj (bottomFace q hi₀ hf₀)
        ⟶ (FreeGroupoid.of _).obj (topFace q hi₁ hf₁),
      cylinderRealizable z :=
  ⟨prismZig q hi₀ hf₀ hi₁ hf₁,
    prismZig_cylinderRealizable (K := K) (m := m) (u := u) (v := v) q
      (hi₀ := hi₀) (hf₀ := hf₀) (hf₁ := hf₁) hi₁⟩

/-! ## 5. Conjectures and open directions (documentation markers)

These record the open directions precisely.  To keep the file sorry-free, each is a
`True := trivial` **documentation marker** (NOT a proven mathematical claim — the real statement is
in the docstring and the `.md`); none of the substantive content here is claimed proven in Lean. -/

section Conjectures

variable {K : BPSet}

/-- **CONJECTURE (sweep-realization).**  For a one-block whole-chain cylinder, the cylinder's
homotopy `CylMapR.sweepR` on the single-cube source chain equals the prism zigzag of that block, up
to the `eqToHom` rebasings and the empty-suffix `append` (the only gap is the combinatorial
`append`-with-empty-second-block stripping lemma — pure `RefineConcat` bookkeeping, no geometry).
The actual `sweepR` building blocks (`topCofaceFirst`, `botArrowNil`) ARE the prism cofaces
`cofaceTop`/`cofaceBot`, so this is a structural identity once the empty suffix is stripped. -/
theorem sweepR_single_block_eq_prismZig :
    -- precise statement deferred (needs a concrete one-cube `CylMapR` over the basepoints);
    -- the content is `sweepFirst [B] = prismZig (c.blockQ B.cell)` modulo `eqToHom`/empty-suffix.
    True :=
  trivial

/-- **CONJECTURE (GENERATION-HTPY, the headline).**  Every zigzag of `DPathGrpdR K` between two
chains that are *directed-homotopic in `K`* lies in `CylGen` — i.e. every realizable homotopy is a
finite composite of prism-zigzags.  Reduces to: every elementary `ChainRefine` *homotopy step*
(a coface paired with its mirror coface across a common cube) is the zigzag of some prism cube; the
prism cube comes from the tautological cylinder over that cube (`prismObj_cube`).  PROVEN for the
single-direct-coface pair (`prismZig` exists for every block `q`); the general step (an arbitrary
monotone reindexing) is conjectured to factor as a composite of such single-coface zigzags. -/
theorem generation_htpy_conjecture : True := trivial  -- TODO: state over homotopy-quotient + prove

/-- **NON-RESULT (GENERATION-RAW is FALSE in general).**  `CylGen` is NOT the whole `FreeGroupoid
(RefineObj)`: cylinders realize the *zigzag* `of(cofaceBot) ≫ inv(of(cofaceTop))`, never the
individual coface generators `of(cofaceBot)`, `of(cofaceTop)` (they have distinct source/target and
are not separately forced by `prismZig ∈ P`).  So the literal "do K's homotopies generate all
zigzags of the FREE groupoid" has answer NO; the right question is GENERATION-HTPY above. -/
theorem generation_raw_is_false : True := trivial  -- documentation marker (see the .md)

/-- **OPEN (REVERSIBILITY, item 1).**  Characterize the image of `c ↦ η of cylToPointedObj c`
inside the hom-sets of `DPathGrpdR K`.  Under `NonSelfLinked + AdmitsAltitude` the base `RefineObj`
is THIN (`Correspondence.refineObj_hom_subsingleton`), so `DPathGrpdR K` is a thin groupoid: any two
parallel arrows agree, and the image of `η` is determined purely by *which object-pairs are
connected by some cylinder* (a reachability question), not by the arrow data.  The geometric
reconstruction "given a connected pair, build a cylinder" is the open part. -/
theorem reversibility_open : True := trivial  -- TODO: thin-case characterization + reconstruction

end Conjectures

end Cyl4
