import CubeChains.Testing.H.HWedge

/-!
# Testing/Pi1/Merges — is the monotone class generated by bead merges?

A wedge map `⋁c ⟶ ⋁a` at total dimension `n` is recorded exactly as in `HWedge`: indexed by the
beads of the **target** `a`, each entry the ordered list of faces its source beads occupy.  Here
that record is given a composition (`wcomp`), the bead merges are generated (`mergesFrom`), and the
sub-category they generate is compared against `W` — the arrows whose fine beads arrive in the
order the coarse bead's decoration prescribes.

Not built by `lake build CubeChains`.
-/

namespace CubeChains

/-! ## The wedge map as a standalone datum

`w : List (List (List ℕ))` — one group per target bead; one increasing face per source bead. -/

/-- The target's bead dimensions. -/
def wtgt (w : List (List (List ℕ))) : List ℕ := w.map fun g => (g.map List.length).sum

/-- The source's bead dimensions. -/
def wsrc (w : List (List (List ℕ))) : List ℕ := w.flatten.map List.length

/-- Total dimension. -/
def wdim (w : List (List (List ℕ))) : ℕ := (wtgt w).sum

/-- **The faces of a group partition the target bead** — at equal total dimension there is no room
for anything else. -/
def wValid (w : List (List (List ℕ))) : Bool :=
  w.all fun g =>
    let f := g.flatten
    let t := (g.map List.length).sum
    f.length == t && (List.range t).all (f.contains ·)

/-- `pos ∘ coordMap` is the identity. -/
def isMono (w : List (List (List ℕ))) : Bool := flatWedge w == List.range (wdim w)

/-! ## The category structure -/

/-- Cut `xs` into consecutive blocks of the prescribed lengths. -/
def regroup {α : Type*} : List ℕ → List α → List (List α)
  | [], _ => []
  | k :: ks, xs => xs.take k :: regroup ks (xs.drop k)

/-- `w₁ ∘ w₂` for `⋁c --w₂--> ⋁b --w₁--> ⋁a`: each source bead of `w₂` lands in the face of `⋁a`
cut out by its `b`-bead's face, and the groups regroup along `w₁`. -/
def wcomp (w₁ w₂ : List (List (List ℕ))) : List (List (List ℕ)) :=
  (regroup (w₁.map List.length) (w₁.flatten.zip w₂)).map fun grp =>
    grp.flatMap fun bg => bg.2.map fun c => c.map fun x => bg.1.getD x 0

/-- The identity of `⋁a`. -/
def wid (a : List ℕ) : List (List (List ℕ)) := a.map fun d => [List.range d]

/-- The bead merges **out of** `⋁b`: fuse beads `j` and `j + 1`, identity elsewhere. -/
def mergesFrom (b : List ℕ) : List (List (List (List ℕ))) :=
  (List.range (b.length - 1)).map fun j =>
    let p := b.getD j 0
    let q := b.getD (j + 1) 0
    (b.take j).map (fun d => [List.range d])
      ++ [[List.range p, (List.range q).map (p + ·)]]
      ++ (b.drop (j + 2)).map (fun d => [List.range d])

/-! ## Enumeration -/

/-- The compositions of `n`. -/
def comps : ℕ → List (List ℕ)
  | 0 => [[]]
  | n + 1 => (List.range (n + 1)).flatMap fun k => (comps (n - k)).map fun c => (k + 1) :: c
decreasing_by omega

/-- The ordered set partitions of `l` into nonempty blocks; `f` is fuel (`l.length` suffices). -/
def ordParts : ℕ → List ℕ → List (List (List ℕ))
  | _, [] => [[]]
  | 0, _ => []
  | f + 1, l =>
      ((l.sublists).filter (!·.isEmpty)).flatMap fun s =>
        (ordParts f (l.filter (!s.contains ·))).map (s :: ·)

/-- The cartesian product of a list of choice-lists. -/
def cartesian {α : Type*} : List (List α) → List (List α)
  | [] => [[]]
  | xs :: rest => xs.flatMap fun x => (cartesian rest).map (x :: ·)

/-- **Every** wedge map at total dimension `n`, built from the combinatorics alone. -/
def allWedges (n : ℕ) : List (List (List (List ℕ))) :=
  (comps n).flatMap fun a => cartesian (a.map fun d => ordParts d (List.range d))

/-- The wedge maps realised by actual `Ch⋆(□ⁿ)` arrows. -/
def realWedges (n : ℕ) : List (List (List (List ℕ))) :=
  ((rows (SubCube.full n) hwedge).map Row.w).eraseDups

/-! ## The sub-category generated by the merges -/

/-- Post-compose the frontier with every merge, until nothing new appears. -/
def mergeGo : ℕ → List (List (List (List ℕ))) → List (List (List (List ℕ))) →
    List (List (List (List ℕ)))
  | 0, _, acc => acc
  | f + 1, frontier, acc =>
      let nxt := (frontier.flatMap fun w => (mergesFrom (wtgt w)).map fun m => wcomp m w).eraseDups
      let new := nxt.filter fun w => !acc.contains w
      if new.isEmpty then acc else mergeGo f new (acc ++ new)

/-- The composites of bead merges at total dimension `n` — identities (length `0`) included. -/
def mergeClosure (n : ℕ) : List (List (List (List ℕ))) :=
  let ids := (comps n).map wid
  mergeGo n ids ids

/-! ## The comparison -/

/-- Set equality of two duplicate-free lists. -/
def setEq {α : Type*} [BEq α] (xs ys : List α) : Bool :=
  xs.all (ys.contains ·) && ys.all (xs.contains ·)

/-- `⟨all, monotone, merge-composites, monotone ∖ merges, merges ∖ monotone⟩`. -/
def verdict (n : ℕ) :
    ℕ × ℕ × ℕ × List (List (List (List ℕ))) × List (List (List (List ℕ))) :=
  let all := allWedges n
  let mono := all.filter isMono
  let mrg := mergeClosure n
  (all.length, mono.length, mrg.length,
    mono.filter fun w => !mrg.contains w,
    mrg.filter fun w => !isMono w)

/-! ## `W`, intrinsically

A morphism groups consecutive fine beads into each coarse bead; `W` is where the fine beads'
directions arrive in the order the coarse bead's own **decoration** prescribes.  No `pos`, no lex
convention — the coordinate test `isMono` is only a computation of this. -/

/-- Per coarse bead: its fine beads' directions, each in **its own** run order, read as positions in
the coarse bead's run.  `W` is where every one of these is `0, 1, …`. -/
def decoSeq {n : ℕ} (X Y : FExec n) : List (List ℕ) :=
  (X.1.zip (groupBeads X.1 Y.1)).map fun bg =>
    bg.2.flatMap fun p => p.map fun d => bg.1.idxOf d

/-- The intrinsic membership test for `W`, on the arrow `Y ⟶ X` of `Ch⋆(□ⁿ)`. -/
def inW {n : ℕ} (X Y : FExec n) : Bool :=
  (decoSeq X Y).all fun s => s == List.range s.length

/-- Arrows where the intrinsic `W`, the coordinate test `isMono ∘ hwedge`, and "the crossing
permutation is trivial" do **not** all agree. -/
def wConflicts (n : ℕ) : List (List (List (Fin n)) × List (List (Fin n))) :=
  ((arrows (SubCube.full n)).filter fun q =>
    !(inW q.1 q.2 == isMono (hwedge q.1 q.2) &&
      inW q.1 q.2 == (FExec.fpermList q.1 q.2 == List.range n))).map fun q => (q.1.1, q.2.1)

/-- Arrows carrying a fine bead whose directions are **not** already increasing in the coarse
bead's run — i.e. where `hwedge`'s `enum` genuinely discards order. -/
def faceOrderWitnesses (n : ℕ) : List (List (List (Fin n)) × List (List (Fin n))) :=
  ((arrows (SubCube.full n)).filter fun q =>
    !((q.1.1.zip (groupBeads q.1.1 q.2.1)).all fun bg =>
      bg.2.all fun p =>
        let u := p.map fun d => bg.1.idxOf d
        u == enum bg.1.length u)).map fun q => (q.1.1, q.2.1)

/-- Arrows whose fine beads do **not** group into consecutive intervals, one per coarse bead, with
matching direction sets — the hypothesis under `hwedge`'s list-of-groups shape. -/
def groupingConflicts (n : ℕ) : List (List (List (Fin n)) × List (List (Fin n))) :=
  ((arrows (SubCube.full n)).filter fun q =>
    let g := groupBeads q.1.1 q.2.1
    (g.flatten != q.2.1) || (g.length != q.1.1.length) ||
      !((q.1.1.zip g).all fun bg =>
        bg.2.flatten.length == bg.1.length && bg.1.all (bg.2.flatten.contains ·))).map
    fun q => (q.1.1, q.2.1)

/-- Composable pairs in `W` whose composite leaves `W` — `W` localizes only if this is empty. -/
def wClosureConflicts (n : ℕ) : List (List (List (List ℕ)) × List (List (List ℕ))) :=
  let ws := (allWedges n).filter isMono
  ws.flatMap fun w₁ =>
    (ws.filter fun w₂ => (wtgt w₂ == wsrc w₁) && !isMono (wcomp w₁ w₂)).map fun w₂ => (w₁, w₂)

/-- The same at the level of arrows: `Z ⟶ Y ⟶ X` with both legs in `W` but the composite out. -/
def wClosureConflictsReal (n : ℕ) : List (List (List (List (Fin n)))) :=
  let xs := execs (SubCube.full n)
  xs.flatMap fun X => xs.flatMap fun Y => xs.flatMap fun Z =>
    if refinesB X.1 Y.1 && refinesB Y.1 Z.1 && inW X Y && inW Y Z && !inW X Z
      then [[X.1, Y.1, Z.1]] else []

/-! ## Validation of the model -/

/-- Composable triples of `Ch⋆(□ⁿ)` on which `wcomp` is **not** the composition of `hwedge` —
`wcomp` earns the name only if this is empty. -/
def compConflicts (n : ℕ) : List (List (List (List (Fin n)))) :=
  let xs := execs (SubCube.full n)
  xs.flatMap fun X => xs.flatMap fun Y => xs.flatMap fun Z =>
    if refinesB X.1 Y.1 && refinesB Y.1 Z.1 &&
        (wcomp (hwedge X Y) (hwedge Y Z) != hwedge X Z)
      then [[X.1, Y.1, Z.1]] else []

/-- The unit laws, over every wedge map at total dimension `n`. -/
def unitConflicts (n : ℕ) : List (List (List (List ℕ))) :=
  (allWedges n).filter fun w =>
    (wcomp (wid (wtgt w)) w != w) || (wcomp w (wid (wsrc w)) != w)

/-- `allWedges n` is exactly the family realised by `Ch⋆(□ⁿ)` — hashed, for `n = 5`. -/
def realMatches (n : ℕ) : Bool :=
  let s := (rows (SubCube.full n) hwedge).foldl
    (fun (s : Std.HashSet (List (List (List ℕ)))) r => s.insert r.w) ∅
  let a := allWedges n
  s.size == a.length && a.all (s.contains ·)

/-! ## The verdict

`wcomp` is the composition of `Ch⋆`, the combinatorial family is exactly the realised one, and the
faces of a group always partition their target bead — so the enumeration is the real thing. -/

#eval ((compConflicts 3).length, (compConflicts 4).length)              -- (0, 0)
#eval ((unitConflicts 3).length, (unitConflicts 4).length,
       (unitConflicts 5).length)                                        -- (0, 0, 0)
#eval (setEq (allWedges 3) (realWedges 3), setEq (allWedges 4) (realWedges 4),
       realMatches 5)                                                   -- (true, true, true)
#eval ((allWedges 4).all wValid, (allWedges 6).all wValid)              -- (true, true)

/-! ## `W` is a class, and it is the coordinate test

The grouping really is by consecutive intervals; the intrinsic `W`, the coordinate test and
"trivial crossing permutation" agree on every arrow; and `W` is closed under composition — as it
must be, since `FExec.fperm_trans` is the cocycle `fperm X Z = fperm Y Z * fperm X Y`. -/

#eval ((groupingConflicts 3).length, (groupingConflicts 4).length,
       (groupingConflicts 5).length)                                    -- (0, 0, 0)
#eval ((wConflicts 3).length, (wConflicts 4).length, (wConflicts 5).length)
                                                                        -- (0, 0, 0)
#eval ((wClosureConflicts 3).length, (wClosureConflicts 4).length,
       (wClosureConflicts 5).length, (wClosureConflicts 6).length)      -- (0, 0, 0, 0)
#eval ((wClosureConflictsReal 3).length, (wClosureConflictsReal 4).length)
                                                                        -- (0, 0)

/-! `enum` is a no-op, and that is why the coordinate test is faithful: `peel`'s side condition is
`p.Sublist b`, so a fine bead's directions *always* arrive in the coarse bead's run order.  The
only freedom left is where the cuts fall, and `W` is "the cuts are the coarse bead's own". -/

#eval ((faceOrderWitnesses 3).length, (faceOrderWitnesses 4).length)    -- (0, 0)
#eval ((arrows (SubCube.full 3)).length,
       (arrows (SubCube.full 3)).all fun q =>
         (q.1.1.zip (groupBeads q.1.1 q.2.1)).all fun bg =>
           bg.2.all fun p => decide (p.Sublist bg.1))                   -- (120, true)

/-! The easy direction: every bead merge is monotone, and `mergesFrom` fuses only **consecutive**
beads — the generators below fuse neighbours in the bead list, nothing wider. -/

#eval ((comps 5).all fun b => (mergesFrom b).all isMono)                -- true

/-! **(M) holds** at every dimension tested: `⟨all, monotone, merge-composites, monotone ∖ merges,
merges ∖ monotone⟩`.  The monotone count is `3 ^ (n - 1)` — one of *uncut / cut in the source only /
cut in both* per junction — against `∑_{a ⊨ n} ∏ⱼ Fub(aⱼ)` wedge maps in all. -/

#eval let v := verdict 3; (v.1, v.2.1, v.2.2.1, v.2.2.2.1, v.2.2.2.2)
                                          -- (20, 9, 9, [], [])
#eval let v := verdict 4; (v.1, v.2.1, v.2.2.1, v.2.2.2.1.length, v.2.2.2.2.length)
                                          -- (120, 27, 27, 0, 0)
#eval let v := verdict 5; (v.1, v.2.1, v.2.2.1, v.2.2.2.1.length, v.2.2.2.2.length)
                                          -- (848, 81, 81, 0, 0)
#eval let v := verdict 6; (v.1, v.2.1, v.2.2.1, v.2.2.2.1.length, v.2.2.2.2.length)
                                          -- (6992, 243, 243, 0, 0)

/-! The smallest non-monotone wedge map: `⋁[1,1] ⟶ ⋁[2]` hitting coordinate `1` first. -/

#eval (isMono [[[1], [0]]], isMono [[[0], [1]]])                        -- (false, true)

end CubeChains

namespace CubeChains

/-! ## Does `W` see its own factors?

If a composite lies in `W`, must both factors?  That is what makes "generated by codimension-one
`W`-morphisms" an induction on `codim` rather than a search. -/

/-- Composable pairs whose composite is in `W` while a factor is not. -/
def wFactorConflicts (n : ℕ) : List (List (List (List ℕ)) × List (List (List ℕ))) :=
  let ws := allWedges n
  ws.flatMap fun w₁ =>
    (ws.filter fun w₂ =>
      (wtgt w₂ == wsrc w₁) && isMono (wcomp w₁ w₂) && !(isMono w₁ && isMono w₂)).map
        fun w₂ => (w₁, w₂)

#eval ((wFactorConflicts 3).length, (wFactorConflicts 4).length,
       (wFactorConflicts 5).length)

end CubeChains
