import CubeChains.Chains.PosLocalization
import CubeChains.Foundations.FibrationLocalize

/-!
# Chains/ElementsFibration — `Ch K` is a category of elements over `Ch Zbp`

`toChZ : Ch K ⥤ Ch Zbp` is a discrete fibration whose fibre over `a` is `⋁a ⟶ K`, so `Ch K` is
the category of elements of `wedgeHoms K = ⋁- ⟶ K` — with an `ᵒᵖ`, mathlib's `Elements` being the
opfibration convention.  `Winf K` is the inverse image of `Winf Zbp`, so `Foundations.
FibrationLocalize` applies: as soon as `wedgeHoms K` inverts the merges, localizing `Ch K` only
localizes the base.
-/

open CategoryTheory Opposite CubeChains BPSet

universe w

namespace ChainCat

variable (K : BPSet)

/-! ### The fibre presheaf -/

/-- The fibre of `toChZ` over a serial wedge: the maps of that wedge into `K`. -/
def wedgeHoms : (Ch Zbp)ᵒᵖ ⥤ Type := serialWedgeInclusion.op ⋙ yoneda.obj K

@[simp] theorem wedgeHoms_map {a b : Ch Zbp} (f : a ⟶ b) (m : (wedgeHoms K).obj (op b)) :
    (wedgeHoms K).map f.op m = f.φ ≫ m := rfl

/-! ### `Ch K` is its category of elements -/

/-- A chain is its dimension sequence together with its classifying map. -/
@[simps] def toElements : Ch K ⥤ ((wedgeHoms K).Elements)ᵒᵖ where
  obj a := op ⟨op (zObj a.dims), a.map⟩
  map {a b} f := (CategoryOfElements.homMk _ _ (zHom f.φ).op f.w).op
  map_id a := Quiver.Hom.unop_inj (CategoryOfElements.ext _ _ _
    (Quiver.Hom.unop_inj (hom_ext' (by simp [zHom_φ]))))
  map_comp f g := Quiver.Hom.unop_inj (CategoryOfElements.ext _ _ _
    (Quiver.Hom.unop_inj (hom_ext' (by simp [zHom_φ]))))

instance : (toElements K).Faithful where
  map_injective h := hom_ext' (by
    have := congrArg (fun u => (Subtype.val (Quiver.Hom.unop u)).unop.φ) h
    simpa [zHom_φ] using this)

instance : (toElements K).Full where
  map_surjective {a b} h :=
    ⟨⟨(h.unop.val).unop.φ, h.unop.property⟩,
      Quiver.Hom.unop_inj (CategoryOfElements.ext _ _ _
        (Quiver.Hom.unop_inj (hom_ext' (by simp [zHom_φ]))))⟩

private theorem wedgeHoms_map_eqToHom {a b : Ch Zbp} (e : a = b) (t : (wedgeHoms K).obj (op a)) :
    (wedgeHoms K).map (eqToHom (congrArg op e)) t
      = eqToHom (congrArg BPSet.serialWedge (congrArg Obj.dims e).symm) ≫ t := by
  subst e; simp

instance : (toElements K).EssSurj where
  mem_essImage x := by
    have e : zObj (unop (unop x).1).dims = unop (unop x).1 := Obj.eq_of_dims rfl
    refine ⟨⟨(unop (unop x).1).dims, (unop x).2⟩, ⟨eqToIso (Opposite.unop_injective ?_)⟩⟩
    refine Functor.Elements.ext _ _ (congrArg op ?_) ?_
    · exact e
    · exact (wedgeHoms_map_eqToHom K e _).trans (Category.id_comp _)

instance : (toElements K).IsEquivalence where

/-- **`Ch K` is the category of elements of `⋁- ⟶ K`.** -/
noncomputable def chEquivElements : Ch K ≌ ((wedgeHoms K).Elements)ᵒᵖ :=
  (toElements K).asEquivalence

/-! ### The merges are pulled back from the base -/

/-- `Winf K` read on the category of elements. -/
theorem Winf_eq_inverseImage_toElements :
    Winf K = ((Winf Zbp).op.inverseImage (CategoryOfElements.π (wedgeHoms K))).op.inverseImage
      (toElements K) := by
  ext a b f
  rw [Winf_eq_inverseImage_toChZ]
  rfl

/-! ### Descent along the merges

`Ch K` localized at `Winf K` is the category of elements of the descended presheaf, as soon as
`⋁- ⟶ K` inverts the merges: all of the `K`-dependence sits in `wedgeHoms K`. -/

section Descent

open CategoryTheory.Localization

/-- The condition the descent needs: a bead merge acts bijectively on the maps of a serial wedge
into `K`. -/
def InvertsMerges (K : BPSet) : Prop := ((Winf Zbp).op).IsInvertedBy (wedgeHoms K)

/-- `Winf` is generated by single merges, so only those need checking. -/
theorem invertsMerges_of_merge
    (h : ∀ {a b : Ch Zbp} (u : a ⟶ b), merge Zbp u → IsIso ((wedgeHoms K).map u.op)) :
    InvertsMerges K := by
  have key : ∀ {a b : Ch Zbp} (u : a ⟶ b), Winf Zbp u → IsIso ((wedgeHoms K).map u.op) := by
    intro a b u hu
    induction hu with
    | of u hu => exact h u hu
    | id x =>
        rw [show (𝟙 x).op = 𝟙 (op x) from rfl, CategoryTheory.Functor.map_id]
        infer_instance
    | comp_of u₁ u₂ _ h₂ ih =>
        haveI := ih
        haveI := h u₂ h₂
        rw [show (u₁ ≫ u₂).op = u₂.op ≫ u₁.op from rfl, CategoryTheory.Functor.map_comp]
        infer_instance
  intro X Y f hf
  exact key f.unop hf

variable (hK : InvertsMerges K)

/-- The merges of `Ch K` read on the category of elements. -/
abbrev elementsWinf : MorphismProperty (wedgeHoms K).Elements :=
  (Winf Zbp).op.inverseImage (CategoryOfElements.π (wedgeHoms K))

/-- `⋁- ⟶ K` descended through the merges of the base. -/
noncomputable abbrev wedgeHomsDescend : ((Winf Zbp).op).Localization ⥤ Type :=
  descend (Winf Zbp).op (wedgeHoms K) hK

/-- `Ch K` compared with the category of elements of the descended presheaf. -/
noncomputable def chDescent : Ch K ⥤ ((wedgeHomsDescend K hK).Elements)ᵒᵖ :=
  toElements K ⋙ (elementsDescent (Winf Zbp).op (wedgeHoms K) hK).op

/-- **Localizing `Ch K` at the merges only localizes the base**, once `⋁- ⟶ K` inverts them. -/
theorem isLocalization_chDescent : (chDescent K hK).IsLocalization (Winf K) := by
  haveI : (elementsDescent (Winf Zbp).op (wedgeHoms K) hK).IsLocalization (elementsWinf K) :=
    isLocalization_elementsDescent _ _ hK
  refine Functor.IsLocalization.of_equivalence_source
    ((elementsDescent (Winf Zbp).op (wedgeHoms K) hK).op) (elementsWinf K).op
    (chDescent K hK) (Winf K) (chEquivElements K).symm ?_ ?_ ?_
  · intro X Y f hf
    refine MorphismProperty.le_isoClosure _ _ ?_
    rw [Winf_eq_inverseImage_toElements]
    change (elementsWinf K).op
      ((chEquivElements K).functor.map ((chEquivElements K).inverse.map f))
    rw [Equivalence.fun_inv_map]
    exact MorphismProperty.RespectsIso.precomp _ ((chEquivElements K).counitIso.app X).hom _
      (MorphismProperty.RespectsIso.postcomp _ ((chEquivElements K).counitIso.app Y).inv _ hf)
  · intro a b f hf
    rw [Winf_eq_inverseImage_toElements] at hf
    exact Localization.inverts ((elementsDescent (Winf Zbp).op (wedgeHoms K) hK).op)
      (elementsWinf K).op _ hf
  · exact (Functor.associator _ _ _).symm ≪≫
      Functor.isoWhiskerRight (chEquivElements K).counitIso _ ≪≫ Functor.leftUnitor _

end Descent

end ChainCat
