import CubeChains.Chains.ChainSkeletal
import Mathlib.CategoryTheory.MorphismProperty.Composition

/-!
# Chains/Fibration — `pushforward` is a discrete fibration

A morphism into `(pushforward g).obj b` has a unique lift ending at `b`: the triangle over `K`
forces the classifying map of its source.  So a factorisation downstairs lifts, and the class
generated by a property of `Ch L` pulls back to the class generated by its inverse image.
-/

open CategoryTheory

namespace ChainCat

variable {K L : BPSet}

/-! ### Rigidity -/

/-- On wedges an identification of chains is one of their dimension sequences; passing `hd := rfl`
collapses it whenever those agree on the nose. -/
theorem eqToHom_φ {a b : Ch K} (h : a = b) (hd : a.dims = b.dims) :
    Hom.φ (eqToHom h) = eqToHom (congrArg BPSet.serialWedge hd) := by
  subst h; simp

/-- A chain morphism is invertible as soon as its wedge map is. -/
theorem isIso_of_isIso_φ {a b : Ch K} (f : a ⟶ b) [IsIso f.φ] : IsIso f :=
  ⟨⟨inv f.φ, by rw [← f.w, ← Category.assoc, IsIso.inv_hom_id, Category.id_comp]⟩,
    hom_ext' (by simp), hom_ext' (by simp)⟩

theorem isIso_φ {a b : Ch K} (f : a ⟶ b) [IsIso f] : IsIso f.φ :=
  ⟨(inv f).φ, by rw [← comp_φ, IsIso.hom_inv_id, id_φ], by rw [← comp_φ, IsIso.inv_hom_id, id_φ]⟩

/-! ### The cartesian lift -/

variable (g : K ⟶ L)

/-- The source of the cartesian lift of `u` at `b`: `c`'s wedge, classified through `b`. -/
def liftObj {b : Ch K} {c : Ch L} (u : c ⟶ (pushforward g).obj b) : Ch K :=
  ⟨c.dims, u.φ ≫ b.map⟩

/-- The cartesian lift of `u` at `b` — the same wedge map, its source classified through `b`. -/
def liftHom {b : Ch K} {c : Ch L} (u : c ⟶ (pushforward g).obj b) : liftObj g u ⟶ b :=
  ⟨u.φ, rfl⟩

theorem pushforward_obj_liftObj {b : Ch K} {c : Ch L} (u : c ⟶ (pushforward g).obj b) :
    (pushforward g).obj (liftObj g u) = c := by
  obtain ⟨cd, cm⟩ := c
  exact Obj.mk_eq_mk rfl (by simpa using u.w)

/-- The lift is forced on objects: the triangle over `K` determines the source's classifying map. -/
theorem liftObj_eq {b : Ch K} {c : Ch L} (u : c ⟶ (pushforward g).obj b) {a : Ch K} (f : a ⟶ b)
    (h : a.dims = c.dims) (hφ : f.φ = eqToHom (congrArg BPSet.serialWedge h) ≫ u.φ) :
    a = liftObj g u := by
  obtain ⟨ad, am⟩ := a
  exact Obj.mk_eq_mk h (by rw [← Category.assoc, ← hφ]; exact f.w.symm)

/-- The lift is forced on morphisms: a chain morphism is its wedge map. -/
instance : (pushforward g).Faithful where
  map_injective := by
    intro _ _ f₁ f₂ h
    have hφ := congrArg (fun m => Hom.φ m) h
    exact hom_ext' hφ

theorem pushforward_map_liftHom {b : Ch K} {c : Ch L} (u : c ⟶ (pushforward g).obj b) :
    (pushforward g).map (liftHom g u) = eqToHom (pushforward_obj_liftObj g u) ≫ u :=
  hom_ext' (by
    simp only [comp_φ, eqToHom_φ (pushforward_obj_liftObj g u) rfl]
    rfl)

/-! ### Lifting a factorisation -/

private theorem prop_eqToHom {C : Type*} [Category C] (P : MorphismProperty C) {a a' b b' : C}
    (ha : a = a') (hb : b = b') (u : a' ⟶ b) : P (eqToHom ha ≫ u ≫ eqToHom hb) ↔ P u := by
  subst ha; subst hb; simp

private theorem closure_of_pushforward {P : MorphismProperty (Ch L)} {c d : Ch L} {u : c ⟶ d}
    (hu : P.multiplicativeClosure u) :
    ∀ (a b : Ch K) (f : a ⟶ b) (ha : (pushforward g).obj a = c)
      (hb : (pushforward g).obj b = d), (pushforward g).map f = eqToHom ha ≫ u ≫ eqToHom hb.symm →
      (P.inverseImage (pushforward g)).multiplicativeClosure f := by
  induction hu with
  | of u hu =>
      intro a b f ha hb hmap
      refine .of f ?_
      change P ((pushforward g).map f)
      rw [hmap]
      exact (prop_eqToHom P ha hb.symm u).mpr hu
  | id x =>
      intro a b f ha hb hmap
      haveI : IsIso ((pushforward g).map f) := by rw [hmap]; infer_instance
      haveI : IsIso f.φ := isIso_φ ((pushforward g).map f)
      haveI := isIso_of_isIso_φ f
      obtain rfl : a = b := eq_of_hom_hom f (inv f)
      rw [endo_eq_id f]
      exact .id a
  | comp_of u₁ u₂ h₁ h₂ ih =>
      intro a b f ha hb hmap
      have hφ : f.φ = Hom.φ (eqToHom ha ≫ u₁) ≫ Hom.φ (u₂ ≫ eqToHom hb.symm) := by
        have h := congrArg Hom.φ hmap
        simp only [comp_φ, Category.assoc] at h ⊢
        exact h
      have hw : Hom.φ (eqToHom ha ≫ u₁) ≫ Hom.φ (u₂ ≫ eqToHom hb.symm) ≫ b.map = a.map := by
        rw [← Category.assoc, ← hφ]; exact f.w
      have hfe : f = (⟨_, hw⟩ : a ⟶ liftObj g (u₂ ≫ eqToHom hb.symm))
          ≫ liftHom g (u₂ ≫ eqToHom hb.symm) := hom_ext' hφ
      rw [hfe]
      refine .comp_of _ _ (ih a _ _ ha (pushforward_obj_liftObj g _) ?_) ?_
      · exact hom_ext' (by
          simp only [comp_φ, eqToHom_φ (pushforward_obj_liftObj g _).symm rfl]
          rfl)
      · change P ((pushforward g).map (liftHom g (u₂ ≫ eqToHom hb.symm)))
        rw [pushforward_map_liftHom]
        exact (prop_eqToHom P _ hb.symm u₂).mpr h₂

/-- **A factorisation downstairs lifts.**  `pushforward g` is a discrete fibration: the cartesian
lift reconstructs each step, so the class `P` generates is the inverse image of the class its
inverse image generates. -/
theorem multiplicativeClosure_inverseImage (P : MorphismProperty (Ch L)) :
    (P.inverseImage (pushforward g)).multiplicativeClosure
      = P.multiplicativeClosure.inverseImage (pushforward g) := by
  refine _root_.le_antisymm ?_ fun a b f hf => closure_of_pushforward g hf a b f rfl rfl (by simp)
  rw [MorphismProperty.multiplicativeClosure_le_iff]
  exact MorphismProperty.monotone_inverseImage _ P.le_multiplicativeClosure

end ChainCat
