import CubeChains.Concurrency.Presentation.CutPresentation
import CubeChains.Concurrency.Presentation.ElementsFibration
import CubeChains.Machinery.Presentation.Elements
import CubeChains.Machinery.Braid.PosAction

/-!
# Concurrency/Presentation/LiftPresentation — the bead cuts of the base, acting on a chain of `K`

`Ch K` is the category of elements of `⋁- ⟶ K` over `Ch Zbp` (`chEquivElements`), so the bead cuts
downstairs act on the chains upstairs: `chCutPoly K` is that total polygraph — 0-cells a shape
carrying a wedge map, 1-cells a bead cut acting on one, 2-cells the base's read on projected words.
It is the alphabet every word of cuts is spelled in.

A **vertex monoid** is not read off it: `End` at a chain is a stabilizer (`chEndEquivStabilizer`),
and `PosBraidAction` shows a stabilizer need not be generated by the generators sitting at its
object — there the generators that are loops are only the identity, while the loops are
`PosPureBraid n`.
-/

open CategoryTheory CategoryTheory.MonoidalCategory Opposite CubeChains BPSet

universe v u

namespace ChainCat

/-- **The 2-polygraph of `Ch K`**: the bead cuts of the base, acting on a chain. -/
noncomputable def chCutPoly (K : BPSet) : Polygraph :=
  zCutPresentation.elementsPoly (wedgeHoms K)

/-! ## The vertex monoids do not follow

`End` at a chain is the stabilizer of its classifying map, `ᵐᵒᵖ` because `Ch K` is the *opposite*
of the category of elements.  A stabilizer is not read off the ambient generators. -/

section Stabilizer

/-- **The loops at a chain are the stabilizer of its classifying map.** -/
noncomputable def chEndEquivStabilizer (K : BPSet) (a : Ch K) :
    End a ≃* (CategoryOfElements.stabilizer (wedgeHoms K)
      (unop ((toElements K).obj a)))ᵐᵒᵖ :=
  ((Functor.FullyFaithful.ofFullyFaithful (toElements K)).mulEquivEnd a).trans
    (CategoryOfElements.endOpEquivStabilizer _ _)

end Stabilizer

/-! ## A stabilizer is not generated by the generators at its object

`PosBraidAction n` is the category of elements of the positive braids acting on the orderings.  Its
generators are the simples `posPerm σ`; the action is free, so the only generator that is a loop is
the identity, while the loops at any ordering are all of `PosPureBraid n`. -/

section Counterexample

open Equiv

variable {n : ℕ}

/-- A simple generator that is a loop is the identity — multiplication is free. -/
theorem eq_id_of_val_eq_posPerm {p : PosBraidAction n} (f : @End (PosBraidAction n) _ p)
    (σ : Perm (Fin n)) (h : f.val = posPerm σ) : f = 𝟙 p := by
  have h2 : posPermHom n f.val * p.back = p.back := f.2
  rw [h, posPermHom_posPerm, mul_eq_right] at h2
  exact Subtype.ext (by rw [h, h2, posPerm_one, ActionCategory.id_val])

/-- **The loops at an ordering are not all trivial** — the square of an atom is pure and nonzero
in the writhe. -/
theorem exists_end_ne_id (hn : 2 ≤ n) (p : PosBraidAction n) :
    ∃ f : @End (PosBraidAction n) _ p, f ≠ 𝟙 p := by
  have hi : 0 < n - 1 := by omega
  set k : Fin (n - 1) := ⟨0, hi⟩ with hk
  have hsq : adjT k * adjT k = 1 := by rw [adjT, swap_mul_self]
  have hfix : posPermHom n (posPerm (adjT k) * posPerm (adjT k)) * p.back = p.back := by
    rw [map_mul, posPermHom_posPerm, hsq, one_mul]
  refine ⟨⟨posPerm (adjT k) * posPerm (adjT k), hfix⟩, ?_⟩
  intro hcon
  have h1 : posPerm (adjT k) * posPerm (adjT k) = 1 :=
    (congrArg Subtype.val hcon).trans (ActionCategory.id_val p)
  have hw : ((permLen (adjT k) : ℤ)) + (permLen (adjT k) : ℤ) = 0 := by
    have h2 := congrArg (Multiplicative.toAdd ∘ posWrithe n) h1
    simpa [← ofAdd_add] using h2
  exact adjT_ne_one k (eq_one_of_permLen_eq_zero _ (by omega))

/-- **The vertex monoid is not generated by the generators sitting at its object.**  Every simple
that is a loop at `p` is the identity, so those generators span the trivial submonoid — while
`End p` is `PosPureBraid n`, which for `n ≥ 2` is not trivial.  A presentation of a total category
therefore says nothing about its `End`s. -/
theorem end_not_generated_by_simples (hn : 2 ≤ n) (p : PosBraidAction n) :
    Submonoid.closure {f : @End (PosBraidAction n) _ p | ∃ σ : Perm (Fin n), f.val = posPerm σ}
      ≠ ⊤ := by
  intro hcon
  obtain ⟨f, hf⟩ := exists_end_ne_id hn p
  have hle : Submonoid.closure
      {f : @End (PosBraidAction n) _ p | ∃ σ : Perm (Fin n), f.val = posPerm σ} ≤ ⊥ := by
    rw [Submonoid.closure_le]
    rintro g ⟨σ, hσ⟩
    exact Submonoid.mem_bot.mpr (eq_id_of_val_eq_posPerm g σ hσ)
  rw [hcon] at hle
  exact hf (Submonoid.mem_bot.mp (hle (Submonoid.mem_top f)))

end Counterexample

end ChainCat
