import CubeChains.Concurrency.Presentation.CellNatural
import CubeChains.Concurrency.Presentation.ArtinDegreeZero
import CubeChains.Concurrency.Presentation.HAction
import CubeChains.Concurrency.Presentation.PaperPoly
import CubeChains.Concurrency.Merge.CubeWeakEquiv

/-!
# Concurrency/Presentation/Statement — the results, without the proof tree

Each `example : T := d` is a claim checked against its proof: the type is the sentence, the term
names where it is proved.  Nothing here is new.

One sentence needs care.  A codimension-two refinement out of a run factors as `run ⟶ mid ⟶ tgt`
with `degree mid = 1`, so the **second leg is not a generator** and each factorisation is read as a
*word*.  That reading is why the braid relation has three letters a side and commutation two.
-/

open CategoryTheory Opposite BPSet CubeChains

namespace ChainCat.Statement

noncomputable section

/-! ## What is inverted

`W` is *generated by* the bead merges.  This is a definition, not a hypothesis — it is the whole
content of "a relatively small class". -/

example (X : BPSet) : W X = (merge X).multiplicativeClosure := rfl

/-! ## Degree zero is the run

`degree a = Σᵢ (dᵢ − 1)` vanishes exactly when every bead is an edge. -/

example (d : Ch Zbp) : degree d = 0 ↔ d = zObj (𝟙^(dimSum d.dims)) :=
  degree_eq_zero_iff_eq_run d

/-! ## The generators are the degree-zero codimension-one refinements

A 1-cell of the presentation is a refinement of codimension one whose *source* is a run — the
polygraph presents `(Ch Zbp)ᵒᵖ`, so `cod` names the refinement's source. -/

example (K : BPSet) {u v : (chContraction K).V} (g : (chContraction K).Gen u v) :
    RunCut g ↔ eltRep g.cod = g.cod := Iff.rfl

/-! ## The relations come from exactly two factorisations

The single geometric input: a codimension-two refinement factors through codimension one in exactly
two ways, and the choice is which of its two boundaries is dropped first.  The middle is pinned by
its *shape*, so this holds over every `K` and not only over the base. -/

example {K : BPSet} {a b : Ch K} (f : a ⟶ b) (hf : codim f = 2) : OneCut f ≃ Bool :=
  oneCutEquivBool f hf

example {K : BPSet} {a b : Ch K} (f : a ⟶ b) : Factorisation f ≃ MidShape a b :=
  factorisationEquiv f

/-! ## The word-reading

The helper that makes "the two factorisations" a statement about *words*: every codimension-one
refinement, conjugated onto the runs, equals a word in the degree-zero ones.  Applied to the second
leg of a factorisation, this is what turns a two-step factorisation into a word of generators. -/

example (K : BPSet) {u v : (chContraction K).V} (g : (chContraction K).Gen u v) :
    ∃ w : Quiver.Path ((chContraction K).poly.pt u) ((chContraction K).poly.pt v),
      Quiver.Path.All (fun ⦃_ _⦄ e => RunCut e) w ∧
      (chContraction K).poly.quot.map w
        = (chContraction K).poly.quot.map (Polygraph.cell g).toPath :=
  ⟨runCellWord g, all_runCellWord g, quot_runCellWord g⟩

/-! ## …spelled in the runs themselves

The same reading, with no `∫F` vocabulary left.  `Paper.poly K` is the polygraph it defines —
0-cells the runs, 1-cells the codimension-one cuts out of them, 2-cells the **degree-two
objects**. -/

example (K : BPSet) : Run K ≃ (chContraction K).V := Paper.runEquiv K

example (K : BPSet) {X : Run K} {b : Ch K} (f : X.chain ⟶ b) (hf : codim f = 2) (ε : Bool) :
    Quiver.Path (Paper.runPt (Paper.bottomRun b)) (Paper.runPt X) :=
  Paper.factorWords f hf ε

/-! A degree-two object needs no morphism beside it: the merge onto it (`Paper.bottomHom`) and that
merge's **complement** (`Run.compl`, the reversal inside every bead) are both functions of the
object, and the complement is the refinement whose two factorisations spell a relation rather than
`w = w`.  So the two words are a function of the object alone. -/

example (K : BPSet) (e : Ch K) (he : degree e = 2) (ε : Bool) :
    Quiver.Path (Paper.runPt (Paper.bottomRun e)) (Paper.runPt (Paper.topOf e).1) :=
  Paper.objWords e he ε

example (K : BPSet) (e : Ch K) : codim (Paper.topOf e).2 = degree e := Paper.codim_topOf e

example {d : List ℕ+} (r : Run (⋁d)) : r.compl.compl = r := Run.compl_compl r

example (K : BPSet) : Polygraph := Paper.poly K

example (K : BPSet) : GenObj (chRunCutSpans K).poly.Gen ⥤q GenObj (Paper.Gen (K := K)) :=
  Paper.runPre

/-! ## The theorem

`Ch(K)[W⁻¹]` is presented by its degree-zero cells, for every `K`, with no hypothesis on `K`. -/

example (K : BPSet) : Presents (chRunCutSpans K).poly (((W K).op).Localization) :=
  chCellPresentation K

/-! ## …and the presentation is a functor of `K`

The polygraph is functorial, and its inclusion into the contracted polygraph is natural on the
nose.  Naturality of the `Presents` relation itself holds only up to isomorphism — a localization
functor is pinned no more tightly than that. -/

example : BPSet ⥤ Polygraph := chCellFunctor

example (K : BPSet) : chCellFunctor.obj K = (chRunCutSpans K).poly := rfl

example {K K' : BPSet} (f : K ⟶ K') :
    (chCellFunctor.map f).functor ⋙ (chRunCutSpans K').incl.functor
      = (chRunCutSpans K).incl.functor ⋙ (chRunFunctor.map f).functor :=
  chCellFunctor_incl f

/-- **The presentation is natural up to isomorphism** — and no more: a localization functor is
pinned only that tightly.  The comparison is canonical, being the unique one restricting along the
localization (`chCutLocPresentationIso_unique`), and it is the identity at the identity. -/
example {K K' : BPSet} (f : K ⟶ K') :
    (chCellFunctor.map f).functor ⋙ (chCellPresentation K').E
      ≅ (chCellPresentation K).E ⋙ chLocOpMap f :=
  chCellPresentationIso f

example (K : BPSet) : chCellPresentationIso (𝟙 K) = eqToIso (chCellSquare_id K) :=
  chCellPresentationIso_id K

/-! ## At the terminal precubical set: Artin

The degree-zero cells at `Zbp` are Artin's, generator to generator and relation to relation. -/

example (N : ℕ) : Fin (N - 1) ≃ RunAtom N := runAtomEquiv N

example (N : ℕ) : AtomPair N ≃ RunSquare N := runSquareEquiv N

example (N : ℕ) :
    Polygraph.loopPoly (RunAtom N) (RunSquare N) (runSrc N) (runTgt N) ≅ artinBP.P N :=
  runRelabel N

/-- Each degree-two shape imposes the Artin relation of its species — **three letters a side for
the hexagon, two for the square**.  That asymmetry is the word-reading above, made visible. -/
example {N : ℕ} (p : AtomPair N) :
    ((p.hi : ℕ) = (p.lo : ℕ) + 1 ∧
        atomLoop N p.lo ≫ atomLoop N p.hi ≫ atomLoop N p.lo
          = atomLoop N p.hi ≫ atomLoop N p.lo ≫ atomLoop N p.hi)
      ∨ ((p.lo : ℕ) + 1 < (p.hi : ℕ) ∧
        atomLoop N p.lo ≫ atomLoop N p.hi = atomLoop N p.hi ≫ atomLoop N p.lo) :=
  runSquare_artin p

/-! ## At a cube: the weak Bruhat order -/

example (n : ℕ) : (W (□n)).Localization ≌ (WeakOrder n)ᵒᵖ := locCubeWeakOrder n

/-! ## At the decorated cube: the positive braid action -/

example (n : ℕ) : (W (Hbp.obj (□n))).Localization ≌ PosBraidAction n := hLocEquiv n

/-! ## What is stated and not proved

The relations as a paper would index them: **one** 2-cell per degree-zero codimension-two
refinement, its two factorisations named by `oneCutEquivBool`.  What is built indexes 2-cells by
*ordered pairs* of factorisations — `Cut.Cell` carries `src` and `tgt` as independent fields, the
diagonal included — so this is the statement that the redundancy collapses.  Defined as a `Prop` and
never proved, so nothing here is assumed. -/

def RelationsAreThePairs (K : BPSet) : Prop :=
  ∀ {u v : (chContraction K).poly.V} (α β : (chRunCutSpans K).poly.Rel ⟨u⟩ ⟨v⟩),
    (chRunCutSpans K).poly.src α = (chRunCutSpans K).poly.src β →
    (chRunCutSpans K).poly.tgt α = (chRunCutSpans K).poly.tgt β → α = β

/-! …and the same gap, read at `Paper.poly`: its 1-cells are the kept cuts (`Paper.runPre`) and its
2-cells are the refinements, so comparing the two presentations is comparing those 2-cells with
`Cut.Cell`'s ordered pairs in both directions.  The forward half is `cutArr_pair`; the backward half
is the collapse above. -/

def PaperPresents (K : BPSet) : Prop :=
  Nonempty (Presents (Paper.poly K) (((W K).op).Localization))

/-! The composition coherence of that isomorphism — the cocycle relating
`chCellPresentationIso (f ≫ g)` to the two factors — is **not** formalized; only the unit case is
(`chCellPresentationIso_id`).  So the family is pseudonatural with half its coherence checked.  No
`Prop` is written for it here: stating it needs the whiskering that the proof would use, and a
placeholder would only look like a conjecture. -/

end

end ChainCat.Statement
