import CubeChains.Concurrency.Presentation.CellNatural
import CubeChains.Concurrency.Presentation.PaperPresents
import CubeChains.Concurrency.Presentation.ArtinDegreeZero
import CubeChains.Concurrency.Presentation.HAction
import CubeChains.Concurrency.Presentation.PaperPoly
import CubeChains.Concurrency.Presentation.PaperFunctor
import CubeChains.Concurrency.Presentation.PaperArtin
import CubeChains.Concurrency.Merge.CubeWeakEquiv

/-!
# Concurrency/Presentation/Statement — the results, without the proof tree

Each `example : T := d` is a claim checked against its proof: the type is the sentence, the term
names where it is proved.  Nothing here is new.

One sentence needs care.  A codimension-two refinement out of a run factors as `run ⟶ mid ⟶ tgt`
with `degree mid = 1`, so the **second leg is not a generator** and each factorisation is read as a
*word*.  That reading is why the braid relation has three letters a side and commutation two.
-/

open CategoryTheory Opposite BPSet CubeChains

namespace ChainCat.Statement

noncomputable section

/-! ## What is inverted

`W` is *generated by* the bead merges.  This is a definition, not a hypothesis — it is the whole
content of "a relatively small class". -/

example (X : BPSet) : W X = (merge X).multiplicativeClosure := rfl

/-! ## Degree zero is the run

`degree a = Σᵢ (dᵢ − 1)` vanishes exactly when every bead is an edge. -/

example (d : Ch Zbp) : degree d = 0 ↔ d = zObj (𝟙^(dimSum d.dims)) :=
  degree_eq_zero_iff_eq_run d

/-! ## The generators are the degree-zero codimension-one refinements

A 1-cell of the presentation is a refinement of codimension one whose *source* is a run — the
polygraph presents `(Ch Zbp)ᵒᵖ`, so `cod` names the refinement's source. -/

example (K : BPSet) {u v : (chContraction K).V} (g : (chContraction K).Gen u v) :
    RunCut g ↔ eltRep g.cod = g.cod := Iff.rfl

/-! ## The relations come from exactly two factorisations

The single geometric input: a codimension-two refinement factors through codimension one in exactly
two ways, and the choice is which of its two boundaries is dropped first.  The middle is pinned by
its *shape*, so this holds over every `K` and not only over the base. -/

example {K : BPSet} {a b : Ch K} (f : a ⟶ b) (hf : codim f = 2) : OneCut f ≃ Bool :=
  oneCutEquivBool f hf

example {K : BPSet} {a b : Ch K} (f : a ⟶ b) : Factorisation f ≃ MidShape a b :=
  factorisationEquiv f

/-! ## The word-reading

The helper that makes "the two factorisations" a statement about *words*: every codimension-one
refinement, conjugated onto the runs, equals a word in the degree-zero ones.  Applied to the second
leg of a factorisation, this is what turns a two-step factorisation into a word of generators. -/

example (K : BPSet) {u v : (chContraction K).V} (g : (chContraction K).Gen u v) :
    ∃ w : Quiver.Path ((chContraction K).poly.pt u) ((chContraction K).poly.pt v),
      Quiver.Path.All (fun ⦃_ _⦄ e => RunCut e) w ∧
      (chContraction K).poly.quot.map w
        = (chContraction K).poly.quot.map (Polygraph.cell g).toPath :=
  ⟨runCellWord g, all_runCellWord g, quot_runCellWord g⟩

/-! ## …spelled in the runs themselves

The same reading, with no `∫F` vocabulary left.  `Paper.poly K` is the polygraph it defines —
0-cells the runs, 1-cells the codimension-one cuts out of them, 2-cells the **degree-two
objects**. -/

example (K : BPSet) : Run K ≃ (chContraction K).V := Paper.runEquiv K

example (K : BPSet) {X : Run K} {b : Ch K} (f : X.chain ⟶ b) (hf : codim f = 2) (ε : Bool) :
    Quiver.Path (Paper.runPt (Paper.bottomRun b)) (Paper.runPt X) :=
  Paper.factorWords f hf ε

/-! A degree-two object needs no morphism beside it: the merge onto it (`Paper.bottomHom`) and its
**greatest** refinement (`Paper.topOf`, the reversal inside every bead) are both functions of the
object, and the greatest one is the refinement whose two factorisations spell a relation rather than
`w = w`.  So the two words are a function of the object alone. -/

example (K : BPSet) (e : Ch K) (he : degree e = 2) (ε : Bool) :
    Quiver.Path (Paper.runPt (Paper.bottomRun e)) (Paper.runPt (Paper.topOf e).1) :=
  Paper.objWords e he ε

example (K : BPSet) (e : Ch K) : codim (Paper.topOf e).2 = degree e := Paper.codim_topOf e

/-! …and "greatest" is a statement about crossings: the reversal inside every bead attains the
capacity `crossCap`, which bounds every refinement out of a run, and the weak order is graded bead
by bead, so nothing else attains it. -/

example (K : BPSet) (e : Ch K) :
    permLen (Paper.runCross (Paper.topOf e).2) = crossCap e.dims :=
  Paper.permLen_runCross_topOf e

example (K : BPSet) {X : Run K} {e : Ch K} (f : X.chain ⟶ e)
    (h : permLen (Paper.runCross f) = crossCap e.dims) : (Paper.topOf e).1 = X :=
  Paper.topOf_fst_eq_of_permLen h

example (K : BPSet) : Polygraph := Paper.poly K

example (K : BPSet) : GenObj (chRunCutSpans K).poly.Gen ⥤q GenObj (Paper.Gen (K := K)) :=
  Paper.runPre

/-! ## The theorem

`Ch(K)[W⁻¹]` is presented by its degree-zero cells, for every `K`, with no hypothesis on `K`. -/

example (K : BPSet) : Presents (chRunCutSpans K).poly (((W K).op).Localization) :=
  chCellPresentation K

/-! ## …and the presentation is a functor of `K`

The polygraph is functorial, and its inclusion into the contracted polygraph is natural on the
nose.  Naturality of the `Presents` relation itself holds only up to isomorphism — a localization
functor is pinned no more tightly than that. -/

example : BPSet ⥤ Polygraph := chCellFunctor

example (K : BPSet) : chCellFunctor.obj K = (chRunCutSpans K).poly := rfl

example {K K' : BPSet} (f : K ⟶ K') :
    (chCellFunctor.map f).functor ⋙ (chRunCutSpans K').incl.functor
      = (chRunCutSpans K).incl.functor ⋙ (chRunFunctor.map f).functor :=
  chCellFunctor_incl f

/-- **The presentation is natural up to isomorphism** — and no more: a localization functor is
pinned only that tightly.  The comparison is canonical, being the unique one restricting along the
localization (`chCutLocPresentationIso_unique`), and it is the identity at the identity. -/
example {K K' : BPSet} (f : K ⟶ K') :
    (chCellFunctor.map f).functor ⋙ (chCellPresentation K').E
      ≅ (chCellPresentation K).E ⋙ chLocOpMap f :=
  chCellPresentationIso f

example (K : BPSet) : chCellPresentationIso (𝟙 K) = eqToIso (chCellSquare_id K) :=
  chCellPresentationIso_id K

/-! ## At the terminal precubical set: Artin

The degree-zero cells at `Zbp` are Artin's, generator to generator and relation to relation — and
they are the paper polygraph's own cells, so the comparison is read there and nowhere else.  A run
of `Zbp` is its strand count, so every cell is a loop and the object it carries is the only datum.

The relation each species imposes on the *arrows* is `artin_of_codim_two`; what the species does to
the *words* — three letters a side for the hexagon, two for the square — is
`Paper.cellWords_eq_artinWords` below. -/

example : Run Zbp ≃ ℕ := Paper.zRunEquiv

example {n : ℕ} {X Y : Run Zbp} (α : Paper.Cell n X Y) : X = Y := α.ends_eq

example (N : ℕ) : Paper.Gen (Paper.zRun N) (Paper.zRun N) ≃ artinBP.S N := Paper.genArtinEquiv N

example (N : ℕ) : Paper.Cell 2 (Paper.zRun N) (Paper.zRun N) ≃ artinBP.Rel N :=
  Paper.relArtinEquiv N

/-- The species as geometry: one bead of dimension three or two of dimension two, and the two cuts
are adjacent exactly in the first case. -/
example {N : ℕ} (α : Paper.Cell 2 (Paper.zRun N) (Paper.zRun N)) :
    ((Paper.cellAtomPairEquiv N α).hi : ℕ) = ((Paper.cellAtomPairEquiv N α).lo : ℕ) + 1
      ↔ (3 : ℕ+) ∈ α.obj.dims :=
  Paper.cell_adj_iff α

example {N : ℕ} (α : Paper.Cell 2 (Paper.zRun N) (Paper.zRun N)) :
    boundaries α.obj.dims = Finset.range (N + 1) \
      {((Paper.cellAtomPairEquiv N α).lo : ℕ) + 1, ((Paper.cellAtomPairEquiv N α).hi : ℕ) + 1} :=
  Paper.boundaries_obj α

/-- **The paper's polygraph at the base *is* Artin's** — cell for cell and word for word, the
`false` side of every 2-cell being its relation's source. -/
example : Paper.poly Zbp ≅ artinBP.poly := Paper.paperArtinIso

example {N : ℕ} (α : Paper.Cell 2 (Paper.zRun N) (Paper.zRun N)) (ε : Bool) :
    Paper.cellWords α ε = (Paper.artinLegPre N).mapPath (MonoidPoly.path (rels := ArtinRel N)
      (cond ε (artinWords (Paper.cellAtomPairEquiv N α)).2
        (artinWords (Paper.cellAtomPairEquiv N α)).1)) :=
  Paper.cellWords_eq_artinWords α ε

/-! ## At a cube: the weak Bruhat order -/

example (n : ℕ) : (W (□n)).Localization ≌ (WeakOrder n)ᵒᵖ := locCubeWeakOrder n

/-! ## At the decorated cube: the positive braid action -/

example (n : ℕ) : (W (Hbp.obj (□n))).Localization ≌ PosBraidAction n := hLocEquiv n

/-! ## The theorem as the paper states it

`Paper.poly K` has the runs for 0-cells, the degree-one objects for 1-cells and the degree-two
objects for 2-cells — no cut, factorisation or `∫F` vocabulary anywhere in its data.  The comparison
`Paper.paperHom` bijects on 0- and 1-cells, and in dimension two each side is derivable from the
other: a kept cell's two words are the two one-cut factorisations of one greatest cut, hence the two
words its object reads, so the ordered pairs the kept cells carry (the flip and the diagonal) add
nothing. -/

example (K : BPSet) : Presents (Paper.poly K) (((W K).op).Localization) :=
  Paper.paperPresents K

/-! …and both that polygraph and the presentation are natural in `K`, the comparison being the
localization's own (`chCellPresentationIso`) and nothing more. -/

example (K : BPSet) : Paper.polyFunctor.obj K = Paper.poly K := rfl

example {K K' : BPSet} (f : K ⟶ K') :
    (Paper.polyFunctor.map f).functor ⋙ (Paper.paperPresents K').E
      ≅ (Paper.paperPresents K).E ⋙ chLocOpMap f :=
  Paper.paperPresentationIso f

/-! ## What is stated and not proved

`Cut.Cell` carries `src` and `tgt` as independent fields, so the contraction's 2-cells are *ordered
pairs* of factorisations, the diagonal included, where a paper would index one 2-cell per
codimension-two refinement.  Nothing collapses that redundancy, and nothing needs to:
`paperPresents`'s 2-cells are the degree-two objects themselves.

The composition coherence of the naturality isomorphism — the cocycle relating
`chCellPresentationIso (f ≫ g)` to the two factors — is **not** formalized; only the unit case is
(`chCellPresentationIso_id`).  So the family is pseudonatural with half its coherence checked.  No
`Prop` is written for it here: stating it needs the whiskering that the proof would use, and a
placeholder would only look like a conjecture. -/

end

end ChainCat.Statement
