import CubeChains.Precubical.Basic.Altitude

/-!
# Precubical/Basic/Reachability

`PrecubicalSet`-level **reachability** of cells and the **connected components**
(`π₀`) of vertices, for an arbitrary `X : PrecubicalSet`.

* `Reaches X` — the inductive one-step reachability relation (`source`/`target`
  faces, closed under `refl`+`trans`), bundled as a `Preorder` (`reachesPreorder`).
* Cell↔vertex: every cell is `ε`-related to its `vertexEnd ε` (`ReachesEnd`, the
  `ε`-oriented reading of `Reaches`), by peeling cofaces (`canonicalMap_peel`).
* `π₀ X` — the quotient of `X.cells 0` by the equivalence relation generated by
  vertex-reachability; `π₀.mapEquiv` turns an isomorphism of precubical sets into
  a bijection of `π₀`'s.
-/

open CategoryTheory Opposite StdCube

namespace PrecubicalSet

/-- The total type of cells of a precubical set across all dimensions. -/
abbrev TotalCell (X : PrecubicalSet) : Type := Σ n, X.cells n

/-- The one-step reachability relation on the cells of a precubical set `X`, in all
dimensions: a *source* face `faceMap false i c` reaches its cell `c`, a cell `c`
reaches each of its *target* faces `faceMap true i c`, closed under reflexivity and
transitivity. -/
inductive Reaches (X : PrecubicalSet) : X.TotalCell → X.TotalCell → Prop
  | refl (x : X.TotalCell) : Reaches X x x
  | source {n} (i : Fin (n + 1)) (c : X.cells (n + 1)) :
      Reaches X ⟨n, X.faceMap false i c⟩ ⟨n + 1, c⟩
  | target {n} (i : Fin (n + 1)) (c : X.cells (n + 1)) :
      Reaches X ⟨n + 1, c⟩ ⟨n, X.faceMap true i c⟩
  | trans {x y z} : Reaches X x y → Reaches X y z → Reaches X x z

/-- `Reaches` read in the direction picked by `ε`: `true` runs along target faces, `false`
backwards along source faces.  Both endpoint statements are one statement in `ε`. -/
def ReachesEnd (X : PrecubicalSet) (ε : Bool) (a b : X.TotalCell) : Prop :=
  cond ε (Reaches X a b) (Reaches X b a)

namespace Reaches

variable {X : PrecubicalSet}

@[refl]
theorem is_refl (x : X.TotalCell) : Reaches X x x := Reaches.refl x

instance : Trans (Reaches X) (Reaches X) (Reaches X) where
  trans := Reaches.trans

end Reaches

namespace ReachesEnd

variable {X : PrecubicalSet}

@[refl]
theorem refl (ε : Bool) (x : X.TotalCell) : ReachesEnd X ε x x := by
  cases ε <;> exact Reaches.refl x

theorem trans {ε : Bool} {x y z : X.TotalCell} (hxy : ReachesEnd X ε x y)
    (hyz : ReachesEnd X ε y z) : ReachesEnd X ε x z := by
  cases ε
  exacts [Reaches.trans hyz hxy, Reaches.trans hxy hyz]

/-- The two face constructors, said once: a cell is `ε`-related to each of its `ε`-faces. -/
theorem face (ε : Bool) {n : ℕ} (i : Fin (n + 1)) (c : X.cells (n + 1)) :
    ReachesEnd X ε ⟨n + 1, c⟩ ⟨n, X.faceMap ε i c⟩ := by
  cases ε
  exacts [Reaches.source i c, Reaches.target i c]

end ReachesEnd

/-- Reachability as a `Preorder` on the total cell type. -/
@[reducible]
def reachesPreorder (X : PrecubicalSet) : Preorder X.TotalCell where
  le := Reaches X
  le_refl := Reaches.refl
  le_trans _ _ _ := Reaches.trans

/-! ### Cell ↔ vertex reachability

We relate the iterated-face vertices `vertexEnd ε` to the inductive
`source`/`target` steps by peeling cofaces (`canonicalMap_peel`), exactly
as `alt_map_eq` peels them for the altitude.  The carried invariant is that every
*fixed* coordinate of the classifying `□ᴺ`-cell takes a single boolean value `ε`,
so each peeled coface is the `ε`-face and the reachability direction is uniform. -/

namespace StdCube

/-- A `□ᴺ`-cell whose every fixed (non-free) coordinate is `ε`. -/
def AllFixed {N k : ℕ} (a : Cell N k) (ε : Bool) : Prop :=
  ∀ j : Fin N, a.val j ≠ none → a.val j = some ε

theorem allFixed_constVertex (N : ℕ) (ε : Bool) :
    AllFixed (constVertex N ε) ε := by
  intro j _; rfl

theorem minFixedVal_of_allFixed {N k : ℕ} (a : Cell N k) (ε : Bool)
    (ha : AllFixed a ε) (h : k < N) : minFixedVal a h = ε := by
  have hne : a.val (minFixed a h) ≠ none := minFixed_val_ne_none a h
  have heq := ha _ hne
  rw [minFixed_val_eq a h] at heq
  exact Option.some.inj heq

theorem allFixed_freeMin {N k : ℕ} (a : Cell N k) (ε : Bool)
    (ha : AllFixed a ε) (h : k < N) : AllFixed (freeMin a h) ε := by
  intro j hj
  rw [freeMin_val] at hj ⊢
  by_cases hjm : j = minFixed a h
  · subst hjm; rw [Function.update_self] at hj; exact absurd rfl hj
  · rw [Function.update_of_ne hjm] at hj ⊢; exact ha j hj

end StdCube

open StdCube

variable {X : PrecubicalSet}

/-- **Peeling reachability.**  If every fixed coordinate of `c' : □ᴺ-cell` is `ε`, then `x`
is `ε`-related to the iterated face `X.map (canonicalMap c').op x`: each coordinate peeled
off by `Cell.peelRec` contributes one `ε`-face. -/
theorem reaches_canonicalMap (ε : Bool) {N : ℕ} (x : X.cells N) :
    ∀ {k : ℕ} (c' : Cell N k), AllFixed c' ε →
      ReachesEnd X ε ⟨N, x⟩ ⟨k, X.map (canonicalMap c').op x⟩ := by
  intro k c'
  induction k, c' using Cell.peelRec with
  | top c' => intro _; rw [X.map_canonicalMap_top x c']
  | step k c' h ih =>
      intro hc'
      refine ReachesEnd.trans (ih (allFixed_freeMin c' ε hc' h)) ?_
      rw [X.map_canonicalMap_peel x c' h, minFixedVal_of_allFixed c' ε hc' h]
      exact ReachesEnd.face ε (minFixedIdx c' h) (X.map (canonicalMap (freeMin c' h)).op x)

/-- Every cell is `ε`-related to its `ε`-extremal vertex. -/
theorem reaches_vertexEnd (ε : Bool) {n : ℕ} (c : X.cells n) :
    ReachesEnd X ε ⟨n, c⟩ ⟨0, X.vertexEnd ε c⟩ :=
  reaches_canonicalMap ε c (constVertex n ε) (allFixed_constVertex n ε)

/-! ### Functoriality

A precubical map `f : X ⟶ Y` carries reachability forward, by induction on the
witness: it commutes with face maps (naturality through cofaces). -/

/-- The action of a precubical map on a total cell. -/
def mapCell {X Y : PrecubicalSet} (f : X ⟶ Y) (x : X.TotalCell) : Y.TotalCell :=
  ⟨x.1, f⟪x.1⟫ x.2⟩

/-- A precubical map carries `faceMap` to `faceMap` (naturality through the coface). -/
theorem map_faceMap {X Y : PrecubicalSet} (f : X ⟶ Y) (ε : Bool) {n : ℕ}
    (i : Fin (n + 1)) (c : X.cells (n + 1)) :
    f⟪n⟫ (X.faceMap ε i c)
      = Y.faceMap ε i (f⟪n + 1⟫ c) :=
  NatTrans.naturality_apply f (coface ε i).op c

/-- **Functoriality of reachability.**  A precubical map `f : X ⟶ Y` preserves
reachability. -/
theorem Reaches.map {X Y : PrecubicalSet} (f : X ⟶ Y) {x y : X.TotalCell}
    (h : Reaches X x y) : Reaches Y (mapCell f x) (mapCell f y) := by
  induction h with
  | refl x => exact Reaches.refl _
  | source i c =>
      change Reaches Y ⟨_, f⟪_⟫ (X.faceMap false i c)⟩ ⟨_, _⟩
      rw [map_faceMap f false i c]
      exact Reaches.source i (f⟪_⟫ c)
  | target i c =>
      change Reaches Y ⟨_, _⟩ ⟨_, f⟪_⟫ (X.faceMap true i c)⟩
      rw [map_faceMap f true i c]
      exact Reaches.target i (f⟪_⟫ c)
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-! ### Connected components of vertices (π₀)

`π₀ X` is the quotient of the `0`-cells (vertices) by the equivalence relation
*generated* by vertex-reachability.  A precubical map induces a map of `π₀`'s, an
isomorphism a bijection. -/

/-- Vertex-reachability: the relation on `0`-cells `v ↦ w` whenever `⟨0,v⟩` reaches
`⟨0,w⟩`. -/
def VertexReaches (X : PrecubicalSet) (v w : X.cells 0) : Prop :=
  Reaches X ⟨0, v⟩ ⟨0, w⟩

/-- The equivalence relation on vertices generated by vertex-reachability. -/
def vertexSetoid (X : PrecubicalSet) : Setoid (X.cells 0) where
  r v w := Relation.EqvGen (VertexReaches X) v w
  iseqv :=
    { refl := fun v => Relation.EqvGen.refl v
      symm := fun h => Relation.EqvGen.symm _ _ h
      trans := fun h₁ h₂ => Relation.EqvGen.trans _ _ _ h₁ h₂ }

/-- **`π₀` of a precubical set**: connected components of its vertices, the quotient
of `0`-cells by the equivalence relation generated by reachability. -/
def π₀ (X : PrecubicalSet) : Type := Quotient X.vertexSetoid

namespace π₀

/-- The class of a vertex in `π₀`. -/
def mk {X : PrecubicalSet} (v : X.cells 0) : π₀ X := Quotient.mk X.vertexSetoid v

@[simp]
theorem mk_surjective {X : PrecubicalSet} : Function.Surjective (π₀.mk (X := X)) :=
  Quotient.mk_surjective

/-- Reachable vertices have equal `π₀` classes. -/
theorem sound {X : PrecubicalSet} {v w : X.cells 0} (h : Reaches X ⟨0, v⟩ ⟨0, w⟩) :
    π₀.mk v = π₀.mk w :=
  Quotient.sound (Relation.EqvGen.rel _ _ h)

/-- A precubical map respects the generating vertex-reachability relation, hence the
generated equivalence. -/
theorem map_eqvGen {X Y : PrecubicalSet} (f : X ⟶ Y) {v w : X.cells 0}
    (h : Relation.EqvGen (VertexReaches X) v w) :
    Relation.EqvGen (VertexReaches Y)
      (f⟪0⟫ v) (f⟪0⟫ w) := by
  induction h with
  | rel a b hab =>
      refine Relation.EqvGen.rel _ _ ?_
      have := (hab : Reaches X ⟨0, a⟩ ⟨0, b⟩).map f
      exact this
  | refl a => exact Relation.EqvGen.refl _
  | symm a b _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans a b c _ _ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

/-- The map on `π₀` induced by a precubical map. -/
def map {X Y : PrecubicalSet} (f : X ⟶ Y) : π₀ X → π₀ Y :=
  Quotient.lift (fun v => π₀.mk (f⟪0⟫ v))
    (fun _ _ h => Quotient.sound (map_eqvGen f h))

@[simp]
theorem map_mk {X Y : PrecubicalSet} (f : X ⟶ Y) (v : X.cells 0) :
    π₀.map f (π₀.mk v) = π₀.mk (f⟪0⟫ v) := rfl

@[simp]
theorem map_id (X : PrecubicalSet) : π₀.map (𝟙 X) = id := by
  funext p
  obtain ⟨v, rfl⟩ := π₀.mk_surjective p
  rfl

theorem map_comp {X Y Z : PrecubicalSet} (f : X ⟶ Y) (g : Y ⟶ Z) :
    π₀.map (f ≫ g) = π₀.map g ∘ π₀.map f := by
  funext p
  obtain ⟨v, rfl⟩ := π₀.mk_surjective p
  rfl

/-- An **isomorphism** of precubical sets induces a **bijection** of `π₀`'s. -/
def mapEquiv {X Y : PrecubicalSet} (e : X ≅ Y) : π₀ X ≃ π₀ Y where
  toFun := π₀.map e.hom
  invFun := π₀.map e.inv
  left_inv p := by
    rw [← Function.comp_apply (f := π₀.map e.inv), ← map_comp, e.hom_inv_id,
      map_id, id_eq]
  right_inv p := by
    rw [← Function.comp_apply (f := π₀.map e.hom), ← map_comp, e.inv_hom_id,
      map_id, id_eq]

end π₀

end PrecubicalSet
