import CubeChains.Braid.Artin
import Mathlib.Order.Fin.Basic
import Mathlib.Order.WellFounded

/-!
# Braid/Generated — adjacent transpositions generate the braid group

`Braid n` is generated by the simple braids `ofPerm (adjT i)`.  The bridge is length-additivity:
every `ofPerm σ` factors, one adjacent descent at a time, into a length-additive product of the
generators (`ofPerm_mem_closure_adjT`), by strong induction on `permLen σ`.
-/

namespace CubeChains

open Equiv

variable {n : ℕ}

/-- A strictly monotone self-map of `Fin n` is the identity (squeezed between `id` and `id`). -/
theorem eq_one_of_strictMono (σ : Perm (Fin n)) (h : StrictMono (⇑σ : Fin n → Fin n)) :
    σ = 1 := by
  refine Equiv.ext fun x => ?_
  change σ x = x
  exact le_antisymm h.apply_le h.le_apply

/-- Adjacent ascent at every step upgrades to full strict monotonicity. -/
theorem strictMono_of_adjacent (σ : Perm (Fin n))
    (h : ∀ i : Fin (n - 1), σ (adjLo i) < σ (adjHi i)) : StrictMono (⇑σ : Fin n → Fin n) := by
  cases n with
  | zero => intro a; exact a.elim0
  | succ m =>
    rw [Fin.strictMono_iff_lt_succ]
    intro i
    have hi := h i
    rwa [show (adjLo i : Fin (m + 1)) = Fin.castSucc i from Fin.ext rfl,
      show (adjHi i : Fin (m + 1)) = Fin.succ i from Fin.ext rfl] at hi

/-- No adjacent descent forces the identity. -/
theorem eq_one_of_no_adjacent_descent (σ : Perm (Fin n))
    (h : ∀ i : Fin (n - 1), ¬ σ (adjHi i) < σ (adjLo i)) : σ = 1 := by
  apply eq_one_of_strictMono
  apply strictMono_of_adjacent
  intro i
  have hne : adjLo i ≠ adjHi i := by
    intro heq
    have := congrArg Fin.val heq
    simp [adjLo_val, adjHi_val] at this
  exact lt_of_le_of_ne (not_lt.mp (h i)) fun heq => hne (σ.injective heq)

/-- A permutation of length `0` is the identity. -/
theorem eq_one_of_permLen_eq_zero (σ : Perm (Fin n)) (h : permLen σ = 0) : σ = 1 := by
  apply eq_one_of_no_adjacent_descent
  intro i hcon
  have hmem : (adjLo i, adjHi i) ∈ inversions σ := by
    simp only [inversions, Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨by rw [Fin.lt_def, adjLo_val, adjHi_val]; omega, hcon⟩
  have hpos : 0 < permLen σ := by rw [permLen]; exact Finset.card_pos.mpr ⟨_, hmem⟩
  omega

/-- A permutation of positive length has an adjacent descent. -/
theorem exists_adjacent_descent (σ : Perm (Fin n)) (h : 0 < permLen σ) :
    ∃ i : Fin (n - 1), σ (adjHi i) < σ (adjLo i) := by
  by_contra hcon
  rw [not_exists] at hcon
  rw [eq_one_of_no_adjacent_descent σ hcon, permLen_one] at h
  exact lt_irrefl 0 h

/-- An adjacent transposition crosses exactly one pair. -/
theorem permLen_adjT (i : Fin (n - 1)) : permLen (adjT i) = 1 := by
  rw [permLen, Finset.card_eq_one]
  refine ⟨(adjLo i, adjHi i), ?_⟩
  ext ⟨p, q⟩
  simp only [inversions, Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_singleton,
    Prod.mk.injEq]
  constructor
  · rintro ⟨hpq, hinv⟩
    exact adjT_inverts i hpq hinv
  · rintro ⟨rfl, rfl⟩
    have hlt : adjLo i < adjHi i := by rw [Fin.lt_def, adjLo_val, adjHi_val]; omega
    exact ⟨hlt, by rw [adjT_hi, adjT_lo]; exact hlt⟩

/-- **Adjacent transpositions generate `Braid n`.**  Every simple braid lies in the subgroup they
generate: peel off one adjacent descent at a time, each step length-additive. -/
theorem ofPerm_mem_closure_adjT (n : ℕ) (σ : Perm (Fin n)) :
    ofPerm σ ∈ Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i))) := by
  set S := Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i))) with hS
  suffices H : ∀ k, ∀ σ : Perm (Fin n), permLen σ = k → ofPerm σ ∈ S from H (permLen σ) σ rfl
  intro k
  induction k using Nat.strongRecOn with
  | ind k ih =>
    intro σ hk
    rcases Nat.eq_zero_or_pos (permLen σ) with h0 | hpos
    · rw [eq_one_of_permLen_eq_zero σ h0, ofPerm_one]
      exact one_mem S
    · obtain ⟨i, hdesc⟩ := exists_adjacent_descent σ hpos
      have hinv2 : adjT i * adjT i = 1 := Equiv.swap_mul_self (adjLo i) (adjHi i)
      have hsimp : σ * adjT i * adjT i = σ := by rw [mul_assoc, hinv2, mul_one]
      have H : ∀ p q : Fin n, p < q → adjT i q < adjT i p →
          (σ * adjT i) (adjT i q) < (σ * adjT i) (adjT i p) := by
        intro p q hpq hinv
        obtain ⟨rfl, rfl⟩ := adjT_inverts i hpq hinv
        simp only [Perm.mul_apply, adjT_hi, adjT_lo]
        exact hdesc
      have key := permLen_mul_of_noDoubleCross (σ := adjT i) (ρ := σ * adjT i) H
      rw [hsimp] at key
      have hadd : permLen σ = permLen (σ * adjT i) + permLen (adjT i) :=
        key.trans (Nat.add_comm _ _)
      have hlt : permLen (σ * adjT i) < permLen σ := by rw [hadd, permLen_adjT]; omega
      have hfact : ofPerm (σ * adjT i) * ofPerm (adjT i) = ofPerm σ := by
        rw [ofPerm_mul (σ := σ * adjT i) (τ := adjT i) (by rw [hsimp]; exact hadd), hsimp]
      rw [← hfact]
      exact mul_mem (ih (permLen (σ * adjT i)) (by omega) (σ * adjT i) rfl)
        (Subgroup.subset_closure (Set.mem_range_self i))

/-- **Adjacent transpositions generate `Braid n`.** -/
theorem Braid.eq_closure_ofPerm_adjT (n : ℕ) :
    Subgroup.closure (Set.range (fun i : Fin (n - 1) => ofPerm (adjT i)))
      = (⊤ : Subgroup (Braid n)) := by
  refine le_antisymm le_top ?_
  rw [← PresentedGroup.closure_range_of (germRels n), Subgroup.closure_le]
  rintro x ⟨σ, rfl⟩
  exact ofPerm_mem_closure_adjT n σ

end CubeChains
