import CubeChains.Braid.Germ
import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.Tactic.Group

/-!
# Braid/Kernel — the kernel of a graded group is generated by its cocycle

A group `G` with `φ : G →* Q` and a *set-section* `t : Q → G` (`φ (t q) = q`, `t 1 = 1`, the `t q`
generating `G`) has

    ker φ = ⟨ t q · t s · t (q·s)⁻¹ ⟩            (`ker_eq_closure_cocycle`)

— Schreier's generators, with the transversal itself as the generating set.  The proof: `H · t q`
is closed under right multiplication by every `t s` and its inverse, because the cocycle is exactly
the defect of `t` from being a homomorphism.

For the braid group `ofPerm` is such a section of `permHom`, and the consumer form (`pureBraid_le`)
asks only for the *conjugated* cocycles `(t A)⁻¹ (t (A·C)) (t C)⁻¹` — the words a four-step zigzag
of refinements reads off, two braids forwards and two backwards.
-/

namespace CubeChains

open Equiv Subgroup

variable {G Q : Type*} [Group G] [Group Q]

/-- The **cocycle** of a set-section `t`: its defect from being a homomorphism. -/
def cocycle (t : Q → G) (q s : Q) : G := t q * t s * (t (q * s))⁻¹

theorem cocycle_mul (t : Q → G) (q s : Q) : cocycle t q s * t (q * s) = t q * t s := by
  rw [cocycle, inv_mul_cancel_right]

/-- The **conjugated cocycle** `(t A)⁻¹ · t (A·C) · (t C)⁻¹`. -/
def cocycle' (t : Q → G) (A C : Q) : G := (t A)⁻¹ * t (A * C) * (t C)⁻¹

/-- The cocycle is a product of two conjugated ones — so a subgroup holding every `cocycle'` holds
every `cocycle`. -/
theorem cocycle_eq_cocycle' (t : Q → G) (ht1 : t 1 = 1) (q s : Q) :
    cocycle t q s = (cocycle' t q⁻¹ q)⁻¹ * cocycle' t q⁻¹ (q * s) := by
  rw [cocycle, cocycle', cocycle', inv_mul_cancel, inv_mul_cancel_left, ht1]
  group

variable {φ : G →* Q} {t : Q → G}

/-- Right multiplication by `t s` moves between cosets of the cocycle group. -/
private theorem inv_cocycle_mul (q s : Q) :
    (cocycle t (q * s⁻¹) s)⁻¹ * t (q * s⁻¹) = t q * (t s)⁻¹ := by
  rw [cocycle, inv_mul_cancel_right, mul_inv_rev, mul_inv_rev, inv_inv]
  group

/-- **The kernel is generated by the cocycle.**  `H · t q` is stable under right multiplication by
the generators — that is what the cocycle measures — and `t 1 = 1` puts the kernel in the `q = 1`
coset. -/
theorem ker_eq_closure_cocycle (ht : ∀ q, φ (t q) = q) (ht1 : t 1 = 1)
    (hgen : Subgroup.closure (Set.range t) = ⊤) :
    φ.ker = Subgroup.closure {g | ∃ q s, g = cocycle t q s} := by
  set H := Subgroup.closure {g | ∃ q s, g = cocycle t q s} with hH
  have hmem : ∀ q s : Q, cocycle t q s ∈ H := fun q s => subset_closure ⟨q, s, rfl⟩
  refine le_antisymm (fun g hg => ?_) ((closure_le _).mpr ?_)
  · -- every `g` lies in `H · t (φ g)`; the kernel sits in the coset of `t 1 = 1`
    have key : ∀ g ∈ Subgroup.closure (Set.range t), ∃ h ∈ H, g = h * t (φ g) := by
      intro g hg'
      induction hg' using Subgroup.closure_induction_right with
      | one => exact ⟨1, one_mem H, by rw [one_mul, map_one, ht1]⟩
      | mul_right x _ y hy ih =>
          obtain ⟨h, hh, hx⟩ := ih
          obtain ⟨s, rfl⟩ := hy
          exact ⟨h * cocycle t (φ x) s, mul_mem hh (hmem _ _), by
            rw [map_mul, ht, mul_assoc, cocycle_mul, ← mul_assoc, ← hx]⟩
      | mul_inv_cancel x _ y hy ih =>
          obtain ⟨h, hh, hx⟩ := ih
          obtain ⟨s, rfl⟩ := hy
          exact ⟨h * (cocycle t (φ x * s⁻¹) s)⁻¹, mul_mem hh (inv_mem (hmem _ _)), by
            rw [map_mul, map_inv, ht, mul_assoc, inv_cocycle_mul, ← mul_assoc, ← hx]⟩
    obtain ⟨h, hh, hgh⟩ := key g (by rw [hgen]; trivial)
    rw [MonoidHom.mem_ker] at hg
    rwa [hgh, hg, ht1, mul_one]
  · rintro _ ⟨q, s, rfl⟩
    simp only [SetLike.mem_coe, MonoidHom.mem_ker, cocycle, map_mul, map_inv, ht, mul_inv_cancel]

/-! ## The braid group -/

/-- **A subgroup holding every conjugated cocycle of `ofPerm` holds the pure braids.**  This is the
algebra the geometry has to meet: a loop of executions produces exactly these words. -/
theorem pureBraid_le {n : ℕ} (H : Subgroup (Braid n))
    (hD : ∀ A C : Perm (Fin n), (ofPerm A)⁻¹ * ofPerm (A * C) * (ofPerm C)⁻¹ ∈ H) :
    PureBraid n ≤ H := by
  rw [show PureBraid n = (permHom n).ker from rfl,
    ker_eq_closure_cocycle (φ := permHom n) (t := ofPerm) permHom_ofPerm ofPerm_one
      (PresentedGroup.closure_range_of _)]
  refine (closure_le _).mpr ?_
  rintro _ ⟨q, s, rfl⟩
  rw [SetLike.mem_coe, cocycle_eq_cocycle' ofPerm ofPerm_one]
  exact mul_mem (inv_mem (hD _ _)) (hD _ _)

end CubeChains
