import CubeChains.Braid.TerminalSaturation
import CubeChains.Braid.TerminalInjProof

/-!
# Braid/TerminalLift — terminal saturation via the null-braid lift

Splits `TerminalSaturation` into a value half (`pureSurj`: the cube braid map hits every pure
braid at the run basepoint — a basepoint transport of `concPureBraidHom_surjective`) and an
asphericity half (`NullLift`: a terminal loop with trivial *braid* comes from a cube loop).

`NullLift` is equivalent to injectivity of `Φ` (`Phi_injective_of_nullLift` /
`nullLift_of_Phi_injective`): the residual crux is exactly terminal-π₁-injectivity, which — per
`CubeCovering`/`CubeTerminalDescent` — is not algebraically reducible to the axiom-free
`concToZAut_injective`.  `RZ_mem_pathAutGenM` is the run-basepoint lollipop generation lemma.
-/

open CategoryTheory CategoryTheory.FreeGroupoid Equiv

namespace CubeChains

section
variable (n : ℕ) (hn : 0 < n)

/-! ## Lollipop generation at the run basepoint

The run-basepoint analogue of `bZ_mem_pathAutGenM`: the canonical path system is run-collapse
onto the run `RZ`, and every vertex loop is a product of the arrow lollipops. -/

/-- The canonical path system at the run basepoint: run-collapse `RZ` onto `x`. -/
noncomputable def pathRZ (x : ConcCat Zbp)
    (m : (FreeGroupoid.mk (RZ n hn) : ConcGrpd Zbp) ⟶ FreeGroupoid.mk x) :
    (FreeGroupoid.mk (RZ n hn) ≅ FreeGroupoid.mk x) :=
  runCollapse (nEvents_eq_of_freeHom m)

theorem pathRZ_RZ (m : (FreeGroupoid.mk (RZ n hn) : ConcGrpd Zbp) ⟶ FreeGroupoid.mk (RZ n hn)) :
    pathRZ n hn (RZ n hn) m = Iso.refl (FreeGroupoid.mk (RZ n hn)) :=
  runCollapse_self (nEvents_eq_of_freeHom m)

/-- **The run vertex group is generated by the canonical arrow loops.**  Every element of
`ConcBraid Zbp (RZ)` is a product of lollipops `pathRZ X ≪≫ homMk e ≪≫ (pathRZ Y)⁻¹`, one per
refinement `e : X ⟶ Y` of `n`-event executions. -/
theorem RZ_mem_pathAutGenM (w : ConcBraid Zbp (RZ n hn)) :
    w ∈ Subgroup.closure (pathAutGenM (RZ n hn) (pathRZ n hn)) :=
  aut_mem_pathAutGenM_closure (RZ n hn) (pathRZ n hn) (pathRZ_RZ n hn) w

/-! ## The reduction

`TerminalSaturation` follows from the two halves. -/

/-- The null-braid lift predicate: a terminal loop whose **braid** is trivial comes from a cube
loop.  This is the residual asphericity crux (see the equivalence with `Φ` injectivity below). -/
def NullLift : Prop :=
  ∀ γ : ConcBraid Zbp (RZ n hn), Φ n hn γ = 1 → γ ∈ (concToZAutRun n hn).range

/-- Terminal saturation from the value half and the null-braid lift: subtract a cube loop
realising `Φ γ`, leaving a null-braid loop that `NullLift` returns to the (subgroup) range. -/
theorem terminalSaturation_of_nullLift
    (pureSurj : ∀ b : Braid n, permHom n b = 1 →
      ∃ δ : ConcBraid (□n) (xRun n hn), Φ n hn (concToZAutRun n hn δ) = b)
    (hlift : NullLift n hn) :
    TerminalSaturation n hn := by
  intro γ hγ
  obtain ⟨δ₀, hδ₀⟩ := pureSurj (Φ n hn γ) hγ
  have h1 : Φ n hn (γ * (concToZAutRun n hn δ₀)⁻¹) = 1 := by
    rw [map_mul, map_inv, hδ₀, mul_inv_cancel]
  obtain ⟨δ₁, hδ₁⟩ := hlift _ h1
  exact ⟨δ₁ * δ₀, by rw [map_mul, hδ₁, inv_mul_cancel_right]⟩

/-! ## The crux is exactly injectivity of `Φ`

`NullLift` is equivalent to injectivity of `Φ` — terminal-π₁-injectivity, the asphericity content
that (per `CubeCovering`/`CubeTerminalDescent`) is not reducible to `concToZAut_injective`. -/

/-- Injectivity of `Φ` gives the null-braid lift (a null-braid loop is trivial, hence in range). -/
theorem nullLift_of_Phi_injective (hΦ : Function.Injective (Φ n hn)) : NullLift n hn := by
  intro γ hγ
  have hγ1 : γ = 1 := hΦ (by rw [hγ, map_one])
  rw [hγ1]
  exact one_mem _

/-- The null-braid lift gives injectivity of `Φ` (`concBraidHom_injective` on the lifted loop). -/
theorem Phi_injective_of_nullLift (hlift : NullLift n hn) : Function.Injective (Φ n hn) := by
  rw [injective_iff_map_eq_one]
  intro γ hγ
  obtain ⟨δ, rfl⟩ := hlift γ hγ
  have hΦ : braidEqHom (nEvents_xRun n hn) (concBraidHom n (xRun n hn) δ) = 1 := by
    rw [← Phi_concToZAutRun n hn δ]; exact hγ
  have hinj : Function.Injective (braidEqHom (nEvents_xRun n hn)) :=
    Function.LeftInverse.injective (g := braidCast (nEvents_xRun n hn).symm)
      (fun y => braidCast_leftInverse (nEvents_xRun n hn) y)
  have hcast : concBraidHom n (xRun n hn) δ = 1 := hinj (hΦ.trans (map_one _).symm)
  have hδ : δ = 1 :=
    concBraidHom_injective n (crossPerm_eq_evPerm n) (xRun n hn) (by rw [hcast, map_one])
  rw [hδ, map_one]

/-- Terminal saturation from the value half and injectivity of the terminal braid map. -/
theorem terminalSaturation_of_Phi_injective
    (pureSurj : ∀ b : Braid n, permHom n b = 1 →
      ∃ δ : ConcBraid (□n) (xRun n hn), Φ n hn (concToZAutRun n hn δ) = b)
    (hΦ : Function.Injective (Φ n hn)) :
    TerminalSaturation n hn :=
  terminalSaturation_of_nullLift n hn pureSurj (nullLift_of_Phi_injective n hn hΦ)

end

end CubeChains
