import CubeChains.Braid.TerminalInj
import CubeChains.Braid.SalQuotZ
import CubeChains.Foundations.QuotientCovering

/-!
# Braid/TerminalInjProof — the two `TerminalInj` obligations at the coarse basepoint

`TerminalInj`'s `LoopMul` (germ relation as a loop equality) and `LoopGen` (the canonical loops
generate) are relations in the free groupoid `ConcGrpd Zbp = FreeGroupoid (ConcCat Zbp)`, whose only
relations come from composition in `ConcCat Zbp` (`FreeGroupoid.homRel`: `homMk (f ≫ g) =
homMk f ≫ homMk g`, `homMk 𝟙 = 𝟙`).

Conjugation by the sequentialization iso `sB : mk bZ ≅ mk RZ` is a group isomorphism
`Aut (mk bZ) ≃* Aut (mk RZ)` carrying the canonical loop `Lσ σ` to the coarse loop `Wσ σ`
("refine `bZ` to the run via `σ`, then un-refine via the standard order").  So each obligation
transports to the single-`[n]`-bead basepoint `bZ` — the vertex group of the braid arrangement of
one bead (`loopMul_iff`, `loopGen_iff`).
-/

open CategoryTheory Opposite Equiv

namespace CubeChains

section Basepoint

variable (n : ℕ) (hn : 0 < n)

/-! ## The sequentialization iso `sB : mk bZ ≅ mk RZ` and the coarse-frame loops `Wσ` -/

/-- The sequentialization iso from the coarse basepoint to the run basepoint. -/
noncomputable def sB : (FreeGroupoid.mk (bZ n hn) : ConcGrpd Zbp) ≅ FreeGroupoid.mk (RZ n hn) :=
  toRunZ (bZ n hn)

/-- The forward leg of `Lσ σ`: refine `bZ` to the run along the order `σ`, identified with `RZ`. -/
noncomputable def Vσ (σ : Perm (Fin n)) :
    (FreeGroupoid.mk (bZ n hn) : ConcGrpd Zbp) ≅ FreeGroupoid.mk (RZ n hn) :=
  asIso (FreeGroupoid.homMk (seqMor (bZ n hn) (lineOf n hn σ)))
    ≪≫ eqToIso (congrArg FreeGroupoid.mk (runL_eq_RZ n hn (lineOf n hn σ)))

/-- **The coarse-frame braiding loop.**  `Wσ σ` is `Lσ σ` conjugated back to the single-`[n]`-bead
basepoint: refine `bZ` to the run via `σ`, then un-refine via the standard order.  It is the
`σ`-generator of the braid arrangement of the single bead. -/
noncomputable def Wσ (σ : Perm (Fin n)) : ConcBraid Zbp (bZ n hn) :=
  Vσ n hn σ ≪≫ (sB n hn).symm

/-- `Lσ σ` factors as "undo the standard sequentialization, then out via `σ`". -/
theorem Lσ_eq (σ : Perm (Fin n)) :
    Lσ n hn σ = (sB n hn).symm ≪≫ Vσ n hn σ := by
  rw [Lσ, loopZ, elemBraidGen, Vσ, sB, toRunZ]
  exact Iso.trans_assoc _ _ _

/-- `Lσ σ` is the coarse loop `Wσ σ` conjugated to the run basepoint by `sB`. -/
theorem Lσ_eq_autConj (σ : Perm (Fin n)) :
    Lσ n hn σ = autConj (sB n hn) (Wσ n hn σ) := by
  rw [Lσ_eq, autConj_apply, Wσ]
  simp only [Iso.trans_assoc, Iso.symm_self_id, Iso.trans_refl]

/-! ## The two obligations, conjugated to the coarse basepoint

Conjugation by the sequentialization iso `sB` is a group isomorphism `Aut (mk bZ) ≃* Aut (mk RZ)`,
so each obligation at `RZ` is equivalent to the same statement about the coarse loops `Wσ` at the
single-`[n]`-bead basepoint `bZ`.  This is where the geometry is cleanest: the vertex group at `bZ`
is the fundamental group of the braid arrangement of one `[n]`-bead. -/

/-- **`LoopMul`, conjugated to the coarse basepoint.**  The germ relation as a loop equality at `RZ`
is equivalent to the same relation among the coarse braiding loops `Wσ` at `bZ`. -/
theorem loopMul_iff :
    LoopMul n hn ↔ ∀ σ τ : Perm (Fin n),
      permLen (σ * τ) = permLen σ + permLen τ → Wσ n hn σ * Wσ n hn τ = Wσ n hn (σ * τ) := by
  constructor
  · intro H σ τ hlen
    have h := H σ τ hlen
    rw [Lσ_eq_autConj, Lσ_eq_autConj, Lσ_eq_autConj, ← map_mul] at h
    exact (autConj (sB n hn)).injective h
  · intro H σ τ hlen
    rw [Lσ_eq_autConj, Lσ_eq_autConj, Lσ_eq_autConj, ← map_mul]
    exact congrArg _ (H σ τ hlen)

/-- **`LoopGen`, conjugated to the coarse basepoint.**  The canonical loops generate the vertex
group at `RZ` iff the coarse loops `Wσ` generate the vertex group at `bZ`. -/
theorem loopGen_iff :
    LoopGen n hn ↔ ∀ w : ConcBraid Zbp (bZ n hn),
      w ∈ Subgroup.closure (Set.range (Wσ n hn)) := by
  have hrange : Set.range (Lσ n hn) = ⇑(autConj (sB n hn)) '' Set.range (Wσ n hn) := by
    rw [← Set.range_comp]
    exact congrArg Set.range (funext (Lσ_eq_autConj n hn))
  have hclos : Subgroup.closure (Set.range (Lσ n hn))
      = (Subgroup.closure (Set.range (Wσ n hn))).map (autConj (sB n hn)).toMonoidHom := by
    rw [hrange, MonoidHom.map_closure, MulEquiv.coe_toMonoidHom]
  constructor
  · intro H w
    have hw : autConj (sB n hn) w ∈ Subgroup.closure (Set.range (Lσ n hn)) := H _
    rw [hclos, Subgroup.mem_map] at hw
    obtain ⟨w', hw'mem, hw'eq⟩ := hw
    rwa [(autConj (sB n hn)).injective hw'eq] at hw'mem
  · intro H a
    rw [hclos, Subgroup.mem_map]
    exact ⟨(autConj (sB n hn)).symm a, H _, (autConj (sB n hn)).apply_symm_apply a⟩

end Basepoint

/-! ## A path system generates the vertex group of a free groupoid

Given a path system `path : ∀ X, mk X₀ ≅ mk X` with `path X₀ = refl`, the vertex group `Aut (mk X₀)`
is generated by the "lollipop" loops `path X ≪≫ homMk e ≪≫ (path Y)⁻¹`, one per arrow `e : X ⟶ Y`
of the base.  Every vertex endo is `wordFunctor.map` of a zigzag word (`wordFunctor_full`); the
induction collapses each letter to a lollipop by inserting `(path Z)⁻¹ ≪≫ path Z`. -/

section Generation

open CategoryTheory CategoryTheory.FreeGroupoid Quiver OrderQuotient

variable {C : Type*} [Category C]

/-- The lollipop generators for a path system: one loop per arrow of `C`. -/
def pathAutGen (X₀ : C) (path : ∀ X : C, (mk X₀ ≅ mk X)) : Set (Aut (mk X₀)) :=
  { g | ∃ (X Y : C) (e : X ⟶ Y), g = path X ≪≫ asIso (homMk e) ≪≫ (path Y).symm }

/-- The backward zigzag letter maps to the inverse generator (bridge to `wordFunctor_map_neg`). -/
theorem wordFunctor_map_toPath_inr {x y : C} (f : x ⟶ y) :
    (wordFunctor C).map (Quiver.Hom.toPath (Sum.inr f : (y ⟶ x) ⊕ (x ⟶ y)))
      = CategoryTheory.inv (homMk f) := by
  have key := wordFunctor_map_neg (C := C) f
  rw [show Quiver.Path.reverse ((posP C).map f)
        = Quiver.Hom.toPath (Sum.inr f : (y ⟶ x) ⊕ (x ⟶ y)) from ?_] at key
  · exact key
  · rw [show (posP C).map f = Quiver.Hom.toPath (Sum.inl f : (x ⟶ y) ⊕ (y ⟶ x)) from rfl,
      Quiver.Path.reverse_toPath]
    rfl

/-- The iso realised by a single symmetrified letter: `homMk` forwards, its inverse backwards. -/
noncomputable def symLetterIso {u v : C} (q : (u ⟶ v) ⊕ (v ⟶ u)) : (mk u ≅ mk v) :=
  q.elim (fun f => asIso (homMk f)) (fun f => (asIso (homMk f)).symm)

theorem symLetterIso_hom {u v : C} (q : (u ⟶ v) ⊕ (v ⟶ u)) :
    (symLetterIso q).hom
      = (wordFunctor C).map ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).map q) := by
  rcases q with f | f
  · change (asIso (homMk f)).hom = _
    rw [asIso_hom]; exact (wordFunctor_map_posP f).symm
  · change (asIso (homMk f)).symm.hom = _
    rw [Iso.symm_hom, asIso_inv]; exact (wordFunctor_map_toPath_inr f).symm

/-- The free-groupoid image of a zigzag word, retyped to `mk`-endpoints so `Aut` group ops fire. -/
noncomputable def wordAsIso (X₀ : C) {b : CategoryTheory.Paths (Quiver.Symmetrify C)}
    (p : (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀ ⟶ b) : (mk X₀ ≅ mk b) :=
  asIso (show (mk X₀ : FreeGroupoid C) ⟶ mk b from (wordFunctor C).map p)

theorem wordAsIso_id (X₀ : C) :
    wordAsIso X₀ (𝟙 ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀))
      = Iso.refl (mk X₀) := by
  apply Iso.ext
  change (wordFunctor C).map (𝟙 ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀))
      = 𝟙 (mk X₀)
  exact (wordFunctor C).map_id _

theorem wordAsIso_comp (X₀ : C) {u v : Quiver.Symmetrify C}
    (p : (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀
        ⟶ (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj u)
    (q : u ⟶ v) :
    wordAsIso X₀ (p ≫ (CategoryTheory.Paths.of (Quiver.Symmetrify C)).map q)
      = wordAsIso X₀ p ≪≫ symLetterIso q := by
  apply Iso.ext
  change (wordFunctor C).map (p ≫ (CategoryTheory.Paths.of (Quiver.Symmetrify C)).map q)
      = (wordAsIso X₀ p).hom ≫ (symLetterIso q).hom
  rw [(wordFunctor C).map_comp, symLetterIso_hom]
  rfl

/-- **Lollipop collapse.**  A zigzag word out of `X₀` folds into a product of lollipop generators
(after capping its far end by `(path b)⁻¹`). -/
theorem pathAut_lollipop (X₀ : C) (path : ∀ X : C, (mk X₀ ≅ mk X))
    (h0 : path X₀ = Iso.refl (mk X₀)) {b : CategoryTheory.Paths (Quiver.Symmetrify C)}
    (p : (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀ ⟶ b) :
    (wordAsIso X₀ p ≪≫ (path b).symm : Aut (mk X₀))
      ∈ Subgroup.closure (pathAutGen X₀ path) := by
  induction p using CategoryTheory.Paths.induction_fixed_source with
  | id =>
      have h1 : (wordAsIso X₀ (𝟙 ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀))
            ≪≫ (path ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)).symm
              : Aut (mk X₀)) = Iso.refl (mk X₀) := by
        rw [wordAsIso_id,
          show path ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)
            = Iso.refl (mk X₀) from h0]
        exact Iso.ext (by simp)
      rw [h1]; exact Subgroup.one_mem (Subgroup.closure (pathAutGen X₀ path))
  | @comp u v p q ih =>
      rw [wordAsIso_comp]
      -- rename the (defeq) `Paths.of`-wrapped target objects to `u`, `v`
      change ((wordAsIso X₀ p ≪≫ symLetterIso q) ≪≫ (path v).symm : Aut (mk X₀))
          ∈ Subgroup.closure (pathAutGen X₀ path)
      -- second lollipop factor is a generator (forward) or its inverse (backward)
      have hB : (path u ≪≫ symLetterIso q ≪≫ (path v).symm : Aut (mk X₀))
          ∈ Subgroup.closure (pathAutGen X₀ path) := by
        rcases q with f | f
        · exact Subgroup.subset_closure ⟨u, v, f, rfl⟩
        · have hgen : (path v ≪≫ asIso (homMk f) ≪≫ (path u).symm : Aut (mk X₀))
              ∈ Subgroup.closure (pathAutGen X₀ path) := Subgroup.subset_closure ⟨v, u, f, rfl⟩
          have hBeq : (path u ≪≫ symLetterIso (Sum.inr f) ≪≫ (path v).symm : Aut (mk X₀))
              = (path v ≪≫ asIso (homMk f) ≪≫ (path u).symm).symm := by
            apply Iso.ext; simp [symLetterIso]
          rw [hBeq]; exact inv_mem hgen
      -- reassociate the loop as (generator) · (inductive tail)
      have hfact : ((wordAsIso X₀ p ≪≫ symLetterIso q) ≪≫ (path v).symm : Aut (mk X₀))
          = (wordAsIso X₀ p ≪≫ (path u).symm)
            ≪≫ (path u ≪≫ symLetterIso q ≪≫ (path v).symm) := by
        apply Iso.ext
        simp
      rw [hfact]
      exact mul_mem hB ih

/-- **Generation lemma.**  Given a path system `path : ∀ X, mk X₀ ≅ mk X` based at `refl`, every
element of the vertex group `Aut (mk X₀)` lies in the subgroup generated by the lollipop loops. -/
theorem aut_mem_pathAutGen_closure (X₀ : C) (path : ∀ X : C, (mk X₀ ≅ mk X))
    (h0 : path X₀ = Iso.refl (mk X₀)) (w : Aut (mk X₀)) :
    w ∈ Subgroup.closure (pathAutGen X₀ path) := by
  obtain ⟨p, hp⟩ := (wordFunctor C).map_surjective
    (X := (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)
    (Y := (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀) w.hom
  have hlolli := pathAut_lollipop X₀ path h0 p
  have hww : (wordAsIso X₀ p
        ≪≫ (path ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)).symm : Aut (mk X₀))
      = w := by
    rw [show path ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)
          = Iso.refl (mk X₀) from h0]
    apply Iso.ext
    change (wordFunctor C).map p ≫ 𝟙 _ = w.hom
    rw [Category.comp_id]; exact hp
  rwa [hww] at hlolli

/-! ## Generation with a partial path system

For a disconnected groupoid a total `path : ∀ X, mk X₀ ≅ mk X` cannot exist.  Reading a connecting
morphism instead lets the path be defined only where `X₀` reaches `X` — the induction supplies the
connecting morphism at every object it visits. -/

/-- Lollipop generators for a path system that reads a connecting morphism. -/
def pathAutGenM (X₀ : C) (path : ∀ X : C, (mk X₀ ⟶ mk X) → (mk X₀ ≅ mk X)) : Set (Aut (mk X₀)) :=
  { g | ∃ (X Y : C) (e : X ⟶ Y) (mX : mk X₀ ⟶ mk X) (mY : mk X₀ ⟶ mk Y),
      g = path X mX ≪≫ asIso (homMk e) ≪≫ (path Y mY).symm }

/-- **Lollipop collapse, partial path.**  The connecting morphism at each object is the word's own
prefix `(wordAsIso X₀ p).hom`. -/
theorem pathAutM_lollipop (X₀ : C) (path : ∀ X : C, (mk X₀ ⟶ mk X) → (mk X₀ ≅ mk X))
    (h0 : ∀ m : (mk X₀ : FreeGroupoid C) ⟶ mk X₀, path X₀ m = Iso.refl (mk X₀))
    {b : CategoryTheory.Paths (Quiver.Symmetrify C)}
    (p : (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀ ⟶ b) :
    (wordAsIso X₀ p ≪≫ (path b (wordAsIso X₀ p).hom).symm : Aut (mk X₀))
      ∈ Subgroup.closure (pathAutGenM X₀ path) := by
  induction p using CategoryTheory.Paths.induction_fixed_source with
  | id =>
      have hone : (wordAsIso X₀ (𝟙 ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀))
            ≪≫ (path ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)
                (wordAsIso X₀ (𝟙 ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀))).hom).symm
              : Aut (mk X₀)) = Iso.refl (mk X₀) := by
        rw [show path ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)
              (wordAsIso X₀ (𝟙 ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀))).hom
              = Iso.refl (mk X₀) from h0 _, wordAsIso_id]
        exact Iso.ext (by simp)
      exact hone ▸ Subgroup.one_mem (Subgroup.closure (pathAutGenM X₀ path))
  | @comp u v p q ih =>
      rw [wordAsIso_comp]
      change ((wordAsIso X₀ p ≪≫ symLetterIso q)
          ≪≫ (path v (wordAsIso X₀ p ≪≫ symLetterIso q).hom).symm : Aut (mk X₀))
          ∈ Subgroup.closure (pathAutGenM X₀ path)
      have hB : (path u (wordAsIso X₀ p).hom ≪≫ symLetterIso q
            ≪≫ (path v (wordAsIso X₀ p ≪≫ symLetterIso q).hom).symm : Aut (mk X₀))
          ∈ Subgroup.closure (pathAutGenM X₀ path) := by
        rcases q with f | f
        · exact Subgroup.subset_closure
            ⟨u, v, f, (wordAsIso X₀ p).hom,
              (wordAsIso X₀ p ≪≫ symLetterIso (Sum.inl f)).hom, rfl⟩
        · have hgen : (path v (wordAsIso X₀ p ≪≫ symLetterIso (Sum.inr f)).hom
                ≪≫ asIso (homMk f) ≪≫ (path u (wordAsIso X₀ p).hom).symm : Aut (mk X₀))
              ∈ Subgroup.closure (pathAutGenM X₀ path) :=
            Subgroup.subset_closure
              ⟨v, u, f, (wordAsIso X₀ p ≪≫ symLetterIso (Sum.inr f)).hom,
                (wordAsIso X₀ p).hom, rfl⟩
          have hBeq : (path u (wordAsIso X₀ p).hom ≪≫ symLetterIso (Sum.inr f)
                ≪≫ (path v (wordAsIso X₀ p ≪≫ symLetterIso (Sum.inr f)).hom).symm : Aut (mk X₀))
              = (path v (wordAsIso X₀ p ≪≫ symLetterIso (Sum.inr f)).hom
                ≪≫ asIso (homMk f) ≪≫ (path u (wordAsIso X₀ p).hom).symm).symm := by
            apply Iso.ext; simp [symLetterIso]
          exact hBeq ▸ inv_mem hgen
      have hfact : ((wordAsIso X₀ p ≪≫ symLetterIso q)
            ≪≫ (path v (wordAsIso X₀ p ≪≫ symLetterIso q).hom).symm : Aut (mk X₀))
          = (wordAsIso X₀ p ≪≫ (path u (wordAsIso X₀ p).hom).symm)
            ≪≫ (path u (wordAsIso X₀ p).hom ≪≫ symLetterIso q
              ≪≫ (path v (wordAsIso X₀ p ≪≫ symLetterIso q).hom).symm) := by
        apply Iso.ext; simp
      exact hfact ▸ mul_mem hB ih

/-- **Generation lemma, partial path.**  Every vertex-group element lies in the subgroup generated
by the lollipop loops of a morphism-reading path system based at `refl`. -/
theorem aut_mem_pathAutGenM_closure (X₀ : C) (path : ∀ X : C, (mk X₀ ⟶ mk X) → (mk X₀ ≅ mk X))
    (h0 : ∀ m : (mk X₀ : FreeGroupoid C) ⟶ mk X₀, path X₀ m = Iso.refl (mk X₀)) (w : Aut (mk X₀)) :
    w ∈ Subgroup.closure (pathAutGenM X₀ path) := by
  obtain ⟨p, hp⟩ := (wordFunctor C).map_surjective
    (X := (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)
    (Y := (CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀) w.hom
  have hlolli := pathAutM_lollipop X₀ path h0 p
  have hww : (wordAsIso X₀ p
        ≪≫ (path ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀)
              (wordAsIso X₀ p).hom).symm : Aut (mk X₀)) = w := by
    rw [show path ((CategoryTheory.Paths.of (Quiver.Symmetrify C)).obj X₀) (wordAsIso X₀ p).hom
          = Iso.refl (mk X₀) from h0 _]
    apply Iso.ext
    change (wordFunctor C).map p ≫ 𝟙 _ = w.hom
    rw [Category.comp_id]; exact hp
  rwa [hww] at hlolli

end Generation

/-! ## The event count is a free-groupoid invariant -/

section Invariant

open CategoryTheory

/-- A morphism between two `Braids` fibres forces equal strand counts (`Braids` is a `Σ`-category:
no morphisms across fibres). -/
theorem strands_hom_index_eq {a b : ℕ} (f : strands a ⟶ strands b) : a = b := by
  cases f; rfl

/-- **The event count is a free-groupoid invariant.**  A morphism `mk x ⟶ mk y` in `ConcGrpd K`
grades (via `braidGrpd`) to a `Braids` morphism, which exists only within one strand-count fibre. -/
theorem nEvents_eq_of_freeHom {K : BPSet} {x y : ConcCat K}
    (f : (FreeGroupoid.mk x : ConcGrpd K) ⟶ FreeGroupoid.mk y) : nEvents x = nEvents y :=
  strands_hom_index_eq ((braidGrpd K).map f)

end Invariant

/-! ## The coarse vertex group is generated by the canonical arrow loops -/

section Reduction

open CategoryTheory

variable (n : ℕ) (hn : 0 < n)

/-- Run-collapse of an execution to itself is the identity: the two runs coincide on the nose. -/
theorem runCollapse_self {x : ConcCat Zbp} (h : nEvents x = nEvents x) :
    runCollapse h = Iso.refl (FreeGroupoid.mk x) := by
  apply Iso.ext
  simp [runCollapse]

/-- The canonical path system at the coarse basepoint: run-collapse `bZ` onto `x` (both have the
same event count, so their runs coincide). -/
noncomputable def pathZ (x : ConcCat Zbp)
    (m : (FreeGroupoid.mk (bZ n hn) : ConcGrpd Zbp) ⟶ FreeGroupoid.mk x) :
    (FreeGroupoid.mk (bZ n hn) ≅ FreeGroupoid.mk x) :=
  runCollapse (nEvents_eq_of_freeHom m)

theorem pathZ_bZ (m : (FreeGroupoid.mk (bZ n hn) : ConcGrpd Zbp) ⟶ FreeGroupoid.mk (bZ n hn)) :
    pathZ n hn (bZ n hn) m = Iso.refl (FreeGroupoid.mk (bZ n hn)) :=
  runCollapse_self (nEvents_eq_of_freeHom m)

/-- **The coarse vertex group is generated by the canonical arrow loops.**  Every element of
`ConcBraid Zbp (bZ)` is a product of loops `pathZ X ≪≫ homMk e ≪≫ (pathZ Y)⁻¹`, one per refinement
`e : X ⟶ Y` of `n`-event executions. -/
theorem bZ_mem_pathAutGenM (w : ConcBraid Zbp (bZ n hn)) :
    w ∈ Subgroup.closure (pathAutGenM (bZ n hn) (pathZ n hn)) :=
  aut_mem_pathAutGenM_closure (bZ n hn) (pathZ n hn) (pathZ_bZ n hn) w

end Reduction

end CubeChains
